# limit_impact_v01：批量评估 D+1 涨跌停/停牌对拟合篮子的影响

本 notebook 参考 `correlation_v04.ipynb` 的任务结构，对观察区间内的每个构建日 D 独立执行完整流程：

1. 使用 D 日权重和收盘价构建 basket1；
2. 使用迅投历史数据识别 D+1 09:31 涨停、跌停、停牌与人工禁买；
3. basket3 在全部指数成分股中排除不可购买股票后重新拟合；
4. 以 D+1 09:31 close 计算 basket1 和 basket3 的偏差；
5. Task11 汇总为 `2 * len(construction_date_ls)` 行的大表，并使用 Plotly 绘制三张交互折线图。

当 `construction_date_ls` 恰好包含两个日期时，两者被解释为观察区间的开始和结束，并使用迅投交易日历展开为闭区间内的全部交易日。本流程不使用同花顺数据源。

## Task0：导入与指数配置

In [15]:
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import pandas as pd
from IPython.display import display
from xtquant import xtdata

xtdata.enable_hello = False
xtdata.reconnect(port=58610)

from utils import (
    LimitImpactDateRun,
    LimitImpactPipelineConfig,
    combine_task11_summaries,
    expand_construction_date_list,
    filter_available_date_runs,
    preflight_transition_daily_data,
    gogoal_query,
    read_daily_data,
)

PROJECT_ROOT = Path.cwd().resolve()

INDEX_CODE = "000300"
INDEX_META = {
    "000016": {"name": "上证50", "xt": "000016.SH"},
    "000300": {"name": "沪深300", "xt": "000300.SH"},
    "000905": {"name": "中证500", "xt": "000905.SH"},
    "000852": {"name": "中证1000", "xt": "000852.SH"},
    "000688": {"name": "科创50", "xt": "000688.SH"},
}
if INDEX_CODE not in INDEX_META:
    raise ValueError(f"INDEX_META 未配置指数 {INDEX_CODE}")

index_name = INDEX_META[INDEX_CODE]["name"]
xt_index_code = INDEX_META[INDEX_CODE]["xt"]
print("项目目录:", PROJECT_ROOT)
print("指数:", INDEX_CODE, index_name)

项目目录: E:\Codex\系统\Stock-Index-Fitting
指数: 000300 沪深300

## Task1：运行参数

`construction_date_ls` 恰好有两个值时，分别为观察开始日和结束日；代码使用迅投上交所日历取闭区间内的全部交易日。边界可以是非交易日，但只有交易日会进入实际运行列表。若列表长度不是 2，则仍按显式构建日列表处理。

In [16]:
# 恰好两个日期时：[观察开始日, 观察结束日]。
construction_date_ls = ["20260701", "20260731"]

# 人工指定的不可购买股票；可为空，对所有日期共用。
manual_unavailable_codes = ["000001"]
# manual_unavailable_codes = []
# manual_unavailable_codes = ["600000", "000001.SZ"]

target_stock_value = 4_500_000.0
rule_file_path = "security_buy_rules.csv"

# 与 correlation_v04 一致的风险模型和优化参数，使用优化后的 Pareto 搜索。
risk_matrix_mode = "correlation"  # "covariance" 或 "correlation"
risk_lookback_days = 5
risk_half_life_days = 3.0
risk_price_col = "lastPrice"

pareto_risk_candidate_count = 10
pareto_amount_candidate_count = 10
pareto_beam_width = 20
pareto_max_rounds = 50
pareto_stale_rounds_to_stop = 3
pareto_legal_neighbor_steps = 3

allow_over_budget = True
max_over_budget_ratio = 1.005

# 迅投原始三角 tick 的既有 NAS 路径。
source_tick_root = Path(r"Z:\高频行情迅投\ticks")
price_validation_tolerance = 0.0001
limit_price_tolerance = 1e-6
include_suspended_as_unavailable = True

construction_date_input_ls = list(construction_date_ls)
construction_date_ls = expand_construction_date_list(
    xtdata,
    construction_date_input_ls,
)

print("输入日期/区间:", construction_date_input_ls)
print("迅投日历展开后的构建日:", construction_date_ls)
print("实际构建日数量:", len(construction_date_ls))

输入日期/区间: ['20260701', '20260731']
迅投日历展开后的构建日: ['20260701', '20260702', '20260703', '20260706', '20260707', '20260708', '20260709', '20260710', '20260713', '20260714', '20260715', '20260716', '20260717', '20260720', '20260721', '20260722', '20260723', '20260724', '20260727', '20260728', '20260729', '20260730', '20260731']
实际构建日数量: 23

## Task2：初始化批量运行与日期隔离目录

每个构建日在 `date_runs/<construction_date>/` 下保留原有的输入、状态、篮子和报表；批量 Task11 结果保存在本次运行根目录的 `04_reports/`。

In [17]:
started_at = datetime.now().astimezone()
import_time = started_at.strftime("%Y%m%d-%H%M%S")
batch_run_dir = (
    PROJECT_ROOT
    / "data"
    / INDEX_CODE
    / f"{import_time}_limit_impact_v01_batch"
)
batch_reports_dir = batch_run_dir / "04_reports"
batch_reports_dir.mkdir(parents=True, exist_ok=True)

pipeline_config = LimitImpactPipelineConfig(
    index_code=INDEX_CODE,
    index_name=index_name,
    xt_index_code=xt_index_code,
    target_stock_value=target_stock_value,
    rule_file_path=rule_file_path,
    manual_unavailable_codes=tuple(manual_unavailable_codes),
    risk_matrix_mode=risk_matrix_mode,
    risk_lookback_days=risk_lookback_days,
    risk_half_life_days=risk_half_life_days,
    risk_price_col=risk_price_col,
    pareto_risk_candidate_count=pareto_risk_candidate_count,
    pareto_amount_candidate_count=pareto_amount_candidate_count,
    pareto_beam_width=pareto_beam_width,
    pareto_max_rounds=pareto_max_rounds,
    pareto_stale_rounds_to_stop=pareto_stale_rounds_to_stop,
    pareto_legal_neighbor_steps=pareto_legal_neighbor_steps,
    allow_over_budget=allow_over_budget,
    max_over_budget_ratio=max_over_budget_ratio,
    source_tick_root=source_tick_root,
    price_validation_tolerance=price_validation_tolerance,
    limit_price_tolerance=limit_price_tolerance,
    include_suspended_as_unavailable=(
        include_suspended_as_unavailable
    ),
)

date_runs = [
    LimitImpactDateRun(
        construction_date=construction_date,
        config=pipeline_config,
        project_root=PROJECT_ROOT,
        batch_run_dir=batch_run_dir,
        import_time=import_time,
        xtdata_client=xtdata,
        gogoal_query_fn=gogoal_query,
        daily_loader=read_daily_data,
    )
    for construction_date in construction_date_ls
]

print("日期数量:", len(date_runs))
print("构建日 -> D+1:")
for run in date_runs:
    print(" ", run.construction_date, "->", run.evaluation_date)
print("批量输出目录:", batch_run_dir)

日期数量: 23
构建日 -> D+1:
  20260701 -> 20260702
  20260702 -> 20260703
  20260703 -> 20260706
  20260706 -> 20260707
  20260707 -> 20260708
  20260708 -> 20260709
  20260709 -> 20260710
  20260710 -> 20260713
  20260713 -> 20260714
  20260714 -> 20260715
  20260715 -> 20260716
  20260716 -> 20260717
  20260717 -> 20260720
  20260720 -> 20260721
  20260721 -> 20260722
  20260722 -> 20260723
  20260723 -> 20260724
  20260724 -> 20260727
  20260727 -> 20260728
  20260728 -> 20260729
  20260729 -> 20260730
  20260730 -> 20260731
  20260731 -> 20260803
批量输出目录: E:\Codex\系统\Stock-Index-Fitting\data\000300\20260807-165523_limit_impact_v01_batch

## Task3：预检日行情/minute cache，再逐日读取权重与交易规则

任一交易日 T 的 NAS 日行情缺失或为空时，同时跳过所有端点触及 T 的区间，即 `前一交易日 -> T` 与 `T -> 下一交易日`。处理方式与 unavailable minute cache 一致：记录、过滤并继续其余区间，不中断批量运行。

In [18]:
# 1. 先处理已存在的 unavailable minute-cache marker。
unavailable_trade_dates = set()
for run in date_runs:
    if set(run.transition_dates) & unavailable_trade_dates:
        continue
    unavailable_trade_dates.update(
        run.existing_unavailable_transition_dates()
    )

date_runs = filter_available_date_runs(
    date_runs,
    unavailable_trade_dates,
)
if not date_runs:
    raise RuntimeError("没有可计算的 D->D+1 区间。")

# 2. 一次性读取每个不同 D/D+1 日期的 NAS 日行情。
#    若 T 缺失，filter_available_date_runs 会同时删除两侧区间。
daily_preflight_input_runs = list(date_runs)
(
    date_runs,
    nas_daily_by_date,
    df_nas_daily_preflight,
) = preflight_transition_daily_data(
    daily_preflight_input_runs,
    read_daily_data,
)
unavailable_nas_daily_dates = set(
    df_nas_daily_preflight.loc[
        ~df_nas_daily_preflight["is_available"],
        "trade_date",
    ]
)
unavailable_trade_dates.update(unavailable_nas_daily_dates)

available_transition_keys = {
    run.transition_dates for run in date_runs
}
df_skipped_nas_daily_transitions = pd.DataFrame(
    [
        {
            "construction_date": run.construction_date,
            "evaluation_date": run.evaluation_date,
            "touching_unavailable_dates": "|".join(
                sorted(
                    set(run.transition_dates)
                    & unavailable_nas_daily_dates
                )
            ),
            "reason": "nas_daily_missing_or_empty",
        }
        for run in daily_preflight_input_runs
        if run.transition_dates not in available_transition_keys
        and set(run.transition_dates) & unavailable_nas_daily_dates
    ],
    columns=[
        "construction_date",
        "evaluation_date",
        "touching_unavailable_dates",
        "reason",
    ],
)
df_nas_daily_preflight.to_csv(
    batch_reports_dir / "nas_daily_preflight.csv",
    index=False,
    encoding="utf-8-sig",
)
df_skipped_nas_daily_transitions.to_csv(
    batch_reports_dir / "skipped_nas_daily_transitions.csv",
    index=False,
    encoding="utf-8-sig",
)

construction_date_ls = [
    run.construction_date for run in date_runs
]
if not date_runs:
    raise RuntimeError(
        "NAS 日行情预检后没有可计算的 D->D+1 区间。"
    )
print("NAS 日行情缺失日:", sorted(unavailable_nas_daily_dates))
print(
    "NAS 日行情导致跳过的区间数:",
    len(df_skipped_nas_daily_transitions),
)

# 3. 仅对日行情可用的区间读取权重和交易规则。
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task3 "
        f"{run.construction_date}"
    )
    run.load_inputs()

# 4. 复用现有 minute-cache 预检，同样删除触及不可用日的区间。
for run in date_runs:
    if set(run.transition_dates) & unavailable_trade_dates:
        continue
    unavailable_trade_dates.update(
        run.preflight_transition_minute_caches()
    )

date_runs = filter_available_date_runs(
    date_runs,
    unavailable_trade_dates,
)
construction_date_ls = [
    run.construction_date for run in date_runs
]
if not date_runs:
    raise RuntimeError("预检后没有可计算的 D->D+1 区间。")
print("预检后有效区间数:", len(date_runs))

if not df_nas_daily_preflight["is_available"].all():
    display(
        df_nas_daily_preflight.loc[
            ~df_nas_daily_preflight["is_available"]
        ]
    )
    display(df_skipped_nas_daily_transitions)

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "evaluation_date": run.evaluation_date,
                "component_count": len(run.stock_codes),
                "raw_weight_sum_pct": run.df_index_weights[
                    "raw_weight_pct"
                ].sum(),
            }
            for run in date_runs
        ]
    )
)

[UNAVAILABLE CACHE HIT] transition preflight 20260720: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_kcb.pkl', 'Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_zb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_zb.pkl'], 'message': "D+1 opening cache 20260717 20260720 requires 4 missing source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_kcb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_zb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_zb.pkl']"}
[UNAVAILABLE CACHE HIT] transition preflight 20260729: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_zb.pkl'], 'message': "tracking stock minute cache 20260729 requires 2 missing tick source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_zb.pkl']"}
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260701.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260702.pkl
  数据形状: (5530, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260703.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260706.pkl
  数据形状: (5527, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260707.pkl
  数据形状: (5527, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260708.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260709.pkl
  数据形状: (5529, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260710.pkl
  数据形状: (5530, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260713.pkl
  数据形状: (5530, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260714.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260715.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260716.pkl
  数据形状: (5529, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260717.pkl
  数据形状: (5528, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260721.pkl
  数据形状: (5529, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260722.pkl
  数据形状: (5530, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260723.pkl
  数据形状: (5530, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260724.pkl
  数据形状: (5531, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260727.pkl
  数据形状: (5533, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260728.pkl
  数据形状: (5533, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260730.pkl
  数据形状: (5534, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\07\A_DAYBAR_20260731.pkl
  数据形状: (5534, 28)
成功读取日行情数据
  文件路径: Z:\高频行情迅投\日行情\2026\08\A_DAYBAR_20260803.pkl
  数据形状: (5535, 28)
NAS 日行情缺失日: []
NAS 日行情导致跳过的区间数: 0
[1/19] Task3 20260701
[2/19] Task3 20260702
[3/19] Task3 20260703
[4/19] Task3 20260706
[5/19] Task3 20260707
[6/19] Task3 20260708
[7/19] Task3 20260709
[8/19] Task3 20260710
[9/19] Task3 20260713
[10/19] Task3 20260714
[11/19] Task3 20260715
[12/19] Task3 20260716
[13/19] Task3 20260721
[14/19] Task3 20260722
[15/19] Task3 20260723
[16/19] Task3 20260724
[17/19] Task3 20260727
[18/19] Task3 20260730
[19/19] Task3 20260731
[CACHE HIT] transition preflight construction 20260701 20260702 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260701 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260702 20260703 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260702 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260703 20260706 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260703 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260706 20260707 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260706 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260707 20260708 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260707 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260708 20260709 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260708 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260709 20260710 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260709 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260710 20260713 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260710 20260713 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260713 20260714 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260713 20260714 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260714 20260715 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260714 20260715 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260715 20260716 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260715 20260716 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260716 20260717 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260716 20260717 20260717: basket_minute_wide_20260717_c859066a4831.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260721 20260722 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260721 20260722 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260722 20260723 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260722 20260723 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260723 20260724 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260723 20260724 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260724 20260727 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260724 20260727 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260727 20260728 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260727 20260728 20260728: basket_minute_wide_20260728_e46fb5fdcd27.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260730 20260731 20260730: basket_minute_wide_20260730_58b1d8f99035.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260730 20260731 20260731: basket_minute_wide_20260731_2db8329b6633.pkl (3.99 MB)
[CACHE HIT] transition preflight construction 20260731 20260803 20260731: basket_minute_wide_20260731_2db8329b6633.pkl (3.99 MB)
[CACHE HIT] transition preflight evaluation 20260731 20260803 20260803: basket_minute_wide_20260803_19aecbe3042d.pkl (3.99 MB)
预检后有效区间数: 19

   construction_date evaluation_date  component_count  raw_weight_sum_pct
0           20260701        20260702              300               100.0
1           20260702        20260703              300               100.0
2           20260703        20260706              300               100.0
3           20260706        20260707              300               100.0
4           20260707        20260708              300               100.0
5           20260708        20260709              300               100.0
6           20260709        20260710              300               100.0
7           20260710        20260713              300               100.0
8           20260713        20260714              300               100.0
9           20260714        20260715              300               100.0
10          20260715        20260716              300               100.0
11          20260716        20260717              300               100.0
12          20260721        20260722              300               100.0
13          20260722        20260723              300               100.0
14          20260723        20260724              300               100.0
15          20260724        20260727              300               100.0
16          20260727        20260728              300               100.0
17          20260730        20260731              300               100.0
18          20260731        20260803              300               100.0

## Task4：逐日读取 D 日指数与成分股收盘价

Go-Goal 为构建价主源，迅投指数日线和 NAS 股票日线用于交叉校验。Task3 已读取并缓存可用日行情，本任务直接复用，不重复读盘。

In [19]:
price_ready_runs = []
late_unavailable_nas_daily_dates = set()
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task4 "
        f"{run.construction_date}"
    )
    nas_daily = nas_daily_by_date.get(run.construction_date)
    if run.load_construction_prices(nas_daily=nas_daily):
        price_ready_runs.append(run)
    else:
        late_unavailable_nas_daily_dates.add(
            run.construction_date
        )

# 即使预检后数据被外部删除，也按同一规则继续，不中断。
unavailable_trade_dates.update(
    late_unavailable_nas_daily_dates
)
date_runs = filter_available_date_runs(
    price_ready_runs,
    late_unavailable_nas_daily_dates,
)
construction_date_ls = [
    run.construction_date for run in date_runs
]
nas_daily_by_date.clear()
del nas_daily_by_date

if not date_runs:
    raise RuntimeError(
        "NAS 日行情过滤后没有可计算的 D->D+1 区间。"
    )

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "construction_index_close": (
                    run.construction_index_close
                ),
                "validated_stock_count": len(
                    run.df_market_snapshot
                ),
            }
            for run in date_runs
        ]
    )
)

[1/19] Task4 20260701

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[2/19] Task4 20260702

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[3/19] Task4 20260703

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[4/19] Task4 20260706

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[5/19] Task4 20260707

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[6/19] Task4 20260708

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[7/19] Task4 20260709

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[8/19] Task4 20260710

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[9/19] Task4 20260713

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[10/19] Task4 20260714

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[11/19] Task4 20260715

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[12/19] Task4 20260716

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[13/19] Task4 20260721

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[14/19] Task4 20260722

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[15/19] Task4 20260723

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[16/19] Task4 20260724

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[17/19] Task4 20260727

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[18/19] Task4 20260730

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

[19/19] Task4 20260731

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

   construction_date  construction_index_close  validated_stock_count
0           20260701                 4958.9773                    300
1           20260702                 4812.2957                    300
2           20260703                 4842.1737                    300
3           20260706                 4841.9980                    300
4           20260707                 4792.2624                    300
5           20260708                 4755.5338                    300
6           20260709                 4876.3125                    300
7           20260710                 4780.7867                    300
8           20260713                 4695.3830                    300
9           20260714                 4796.5020                    300
10          20260715                 4786.7828                    300
11          20260716                 4698.4344                    300
12          20260721                 4739.2287                    300
13          20260722                 4717.2442                    300
14          20260723                 4728.0018                    300
15          20260724                 4649.1917                    300
16          20260727                 4702.4272                    300
17          20260730                 4549.7201                    300
18          20260731                 4588.1968                    300

## Task5：逐日构建理论组合与风险矩阵

In [20]:
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task5 "
        f"{run.construction_date}"
    )
    run.build_risk_model()

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "requested_risk_dates": run.risk_dates,
                "used_risk_dates": run.used_risk_dates,
                "skipped_risk_dates": run.skipped_risk_dates,
                "risk_matrix_shape": run.risk_matrix.shape,
                "oas_shrinkage": run.risk_model.summary[
                    "oas_shrinkage"
                ],
            }
            for run in date_runs
        ]
    )
)

[1/19] Task5 20260701
[CACHE HIT] risk cache 20260625 20260625: basket_minute_wide_20260625_f2653c108899.pkl (3.99 MB)
[CACHE HIT] risk cache 20260626 20260626: basket_minute_wide_20260626_e075d94ff3c9.pkl (3.99 MB)
[CACHE HIT] risk cache 20260629 20260629: basket_minute_wide_20260629_2d4119158d06.pkl (3.99 MB)
[CACHE HIT] risk cache 20260630 20260630: basket_minute_wide_20260630_353f712e13f0.pkl (3.99 MB)
[CACHE HIT] risk cache 20260701 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[Risk fallback 20260629] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260630] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260701] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[2/19] Task5 20260702
[CACHE HIT] risk cache 20260626 20260626: basket_minute_wide_20260626_e075d94ff3c9.pkl (3.99 MB)
[CACHE HIT] risk cache 20260629 20260629: basket_minute_wide_20260629_2d4119158d06.pkl (3.99 MB)
[CACHE HIT] risk cache 20260630 20260630: basket_minute_wide_20260630_353f712e13f0.pkl (3.99 MB)
[CACHE HIT] risk cache 20260701 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[CACHE HIT] risk cache 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[Risk fallback 20260629] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260630] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260701] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260702] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[3/19] Task5 20260703
[CACHE HIT] risk cache 20260629 20260629: basket_minute_wide_20260629_2d4119158d06.pkl (3.99 MB)
[CACHE HIT] risk cache 20260630 20260630: basket_minute_wide_20260630_353f712e13f0.pkl (3.99 MB)
[CACHE HIT] risk cache 20260701 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[CACHE HIT] risk cache 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] risk cache 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[Risk fallback 20260629] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260630] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260701] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260702] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260703] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[4/19] Task5 20260706
[CACHE HIT] risk cache 20260630 20260630: basket_minute_wide_20260630_353f712e13f0.pkl (3.99 MB)
[CACHE HIT] risk cache 20260701 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[CACHE HIT] risk cache 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] risk cache 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] risk cache 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[Risk fallback 20260630] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260701] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260702] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260703] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260706] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[5/19] Task5 20260707
[CACHE HIT] risk cache 20260701 20260701: basket_minute_wide_20260701_bfeca5272447.pkl (3.99 MB)
[CACHE HIT] risk cache 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] risk cache 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] risk cache 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] risk cache 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[Risk fallback 20260701] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260702] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260703] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260706] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260707] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[6/19] Task5 20260708
[CACHE HIT] risk cache 20260702 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[CACHE HIT] risk cache 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] risk cache 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] risk cache 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] risk cache 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[Risk fallback 20260702] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260703] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260706] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260707] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260708] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[7/19] Task5 20260709
[CACHE HIT] risk cache 20260703 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[CACHE HIT] risk cache 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] risk cache 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] risk cache 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] risk cache 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[Risk fallback 20260703] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260706] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260707] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260708] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260709] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[8/19] Task5 20260710
[CACHE HIT] risk cache 20260706 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[CACHE HIT] risk cache 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] risk cache 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] risk cache 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[Risk fallback 20260706] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260707] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260708] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260709] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260710] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[9/19] Task5 20260713
[CACHE HIT] risk cache 20260707 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[CACHE HIT] risk cache 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] risk cache 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] risk cache 20260713 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[Risk fallback 20260707] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260708] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260709] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260710] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[10/19] Task5 20260714
[CACHE HIT] risk cache 20260708 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[CACHE HIT] risk cache 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] risk cache 20260713 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[CACHE HIT] risk cache 20260714 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[Risk fallback 20260708] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260709] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260710] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[11/19] Task5 20260715
[CACHE HIT] risk cache 20260709 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] risk cache 20260713 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[CACHE HIT] risk cache 20260714 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[CACHE HIT] risk cache 20260715 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[Risk fallback 20260709] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[Risk fallback 20260710] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[12/19] Task5 20260716
[CACHE HIT] risk cache 20260710 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[CACHE HIT] risk cache 20260713 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[CACHE HIT] risk cache 20260714 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[CACHE HIT] risk cache 20260715 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[CACHE HIT] risk cache 20260716 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[Risk fallback 20260710] 使用 lastClose 填充全天无有效 lastPrice 的股票，共 1 只：['688072.SH']
[13/19] Task5 20260721
[CACHE HIT] risk cache 20260715 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[CACHE HIT] risk cache 20260716 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[CACHE HIT] risk cache 20260717 20260717: basket_minute_wide_20260717_c859066a4831.pkl (3.99 MB)
[UNAVAILABLE CACHE HIT] risk cache 20260720 20260720: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_kcb.pkl', 'Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_zb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_zb.pkl'], 'message': "D+1 opening cache 20260717 20260720 requires 4 missing source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_kcb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_zb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260721 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[14/19] Task5 20260722
[CACHE HIT] risk cache 20260716 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[CACHE HIT] risk cache 20260717 20260717: basket_minute_wide_20260717_c859066a4831.pkl (3.99 MB)
[UNAVAILABLE CACHE HIT] risk cache 20260720 20260720: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_kcb.pkl', 'Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_zb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_zb.pkl'], 'message': "D+1 opening cache 20260717 20260720 requires 4 missing source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_kcb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_zb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260721 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[CACHE HIT] risk cache 20260722 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[15/19] Task5 20260723
[CACHE HIT] risk cache 20260717 20260717: basket_minute_wide_20260717_c859066a4831.pkl (3.99 MB)
[UNAVAILABLE CACHE HIT] risk cache 20260720 20260720: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_kcb.pkl', 'Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_zb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_zb.pkl'], 'message': "D+1 opening cache 20260717 20260720 requires 4 missing source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_kcb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_zb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260721 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[CACHE HIT] risk cache 20260722 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260723 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[16/19] Task5 20260724
[UNAVAILABLE CACHE HIT] risk cache 20260720 20260720: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_kcb.pkl', 'Z:\\高频行情迅投\\ticks\\SH\\2026\\07\\20260720_tick_sh_zb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260720_tick_sz_zb.pkl'], 'message': "D+1 opening cache 20260717 20260720 requires 4 missing source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_kcb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SH\\\\2026\\\\07\\\\20260720_tick_sh_zb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260720_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260721 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[CACHE HIT] risk cache 20260722 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260723 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[CACHE HIT] risk cache 20260724 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[17/19] Task5 20260727
[CACHE HIT] risk cache 20260721 20260721: basket_minute_wide_20260721_93afefac3799.pkl (3.99 MB)
[CACHE HIT] risk cache 20260722 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[CACHE HIT] risk cache 20260723 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[CACHE HIT] risk cache 20260724 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[CACHE HIT] risk cache 20260727 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[18/19] Task5 20260730
[CACHE HIT] risk cache 20260724 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[CACHE HIT] risk cache 20260727 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[CACHE HIT] risk cache 20260728 20260728: basket_minute_wide_20260728_e46fb5fdcd27.pkl (3.99 MB)
[UNAVAILABLE CACHE HIT] risk cache 20260729 20260729: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_zb.pkl'], 'message': "tracking stock minute cache 20260729 requires 2 missing tick source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260730 20260730: basket_minute_wide_20260730_58b1d8f99035.pkl (3.99 MB)
[19/19] Task5 20260731
[CACHE HIT] risk cache 20260727 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[CACHE HIT] risk cache 20260728 20260728: basket_minute_wide_20260728_e46fb5fdcd27.pkl (3.99 MB)
[UNAVAILABLE CACHE HIT] risk cache 20260729 20260729: reason=source_file_missing; details={'source_files': ['Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_cyb.pkl', 'Z:\\高频行情迅投\\ticks\\SZ\\2026\\07\\20260729_tick_sz_zb.pkl'], 'message': "tracking stock minute cache 20260729 requires 2 missing tick source file(s): ['Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_cyb.pkl', 'Z:\\\\高频行情迅投\\\\ticks\\\\SZ\\\\2026\\\\07\\\\20260729_tick_sz_zb.pkl']"}
[CACHE HIT] risk cache 20260730 20260730: basket_minute_wide_20260730_58b1d8f99035.pkl (3.99 MB)
[CACHE HIT] risk cache 20260731 20260731: basket_minute_wide_20260731_2db8329b6633.pkl (3.99 MB)

,construction_date,requested_risk_dates,used_risk_dates,skipped_risk_dates,risk_matrix_shape,oas_shrinkage
0,20260701,"[20260625, 20260626, 20260629, 20260630, 20260...","[20260625, 20260626, 20260629, 20260630, 20260...",[],"(300, 300)",0.029701
1,20260702,"[20260626, 20260629, 20260630, 20260701, 20260...","[20260626, 20260629, 20260630, 20260701, 20260...",[],"(300, 300)",0.024132
2,20260703,"[20260629, 20260630, 20260701, 20260702, 20260...","[20260629, 20260630, 20260701, 20260702, 20260...",[],"(300, 300)",0.020576
3,20260706,"[20260630, 20260701, 20260702, 20260703, 20260...","[20260630, 20260701, 20260702, 20260703, 20260...",[],"(300, 300)",0.018401
4,20260707,"[20260701, 20260702, 20260703, 20260706, 20260...","[20260701, 20260702, 20260703, 20260706, 20260...",[],"(300, 300)",0.016044
5,20260708,"[20260702, 20260703, 20260706, 20260707, 20260...","[20260702, 20260703, 20260706, 20260707, 20260...",[],"(300, 300)",0.012864
6,20260709,"[20260703, 20260706, 20260707, 20260708, 20260...","[20260703, 20260706, 20260707, 20260708, 20260...",[],"(300, 300)",0.013993
7,20260710,"[20260706, 20260707, 20260708, 20260709, 20260...","[20260706, 20260707, 20260708, 20260709, 20260...",[],"(300, 300)",0.015036
8,20260713,"[20260707, 20260708, 20260709, 20260710, 20260...","[20260707, 20260708, 20260709, 20260710, 20260...",[],"(300, 300)",0.013484
9,20260714,"[20260708, 20260709, 20260710, 20260713, 20260...","[20260708, 20260709, 20260710, 20260713, 20260...",[],"(300, 300)",0.010723
10,20260715,"[20260709, 20260710, 20260713, 20260714, 20260...","[20260709, 20260710, 20260713, 20260714, 20260...",[],"(300, 300)",0.011286
11,20260716,"[20260710, 20260713, 20260714, 20260715, 20260...","[20260710, 20260713, 20260714, 20260715, 20260...",[],"(300, 300)",0.010723
12,20260721,"[20260715, 20260716, 20260717, 20260720, 20260...","[20260715, 20260716, 20260717, 20260721]",[20260720],"(300, 300)",0.011006
13,20260722,"[20260716, 20260717, 20260720, 20260721, 20260...","[20260716, 20260717, 20260721, 20260722]",[20260720],"(300, 300)",0.010828
14,20260723,"[20260717, 20260720, 20260721, 20260722, 20260...","[20260717, 20260721, 20260722, 20260723]",[20260720],"(300, 300)",0.011086
15,20260724,"[20260720, 20260721, 20260722, 20260723, 20260...","[20260721, 20260722, 20260723, 20260724]",[20260720],"(300, 300)",0.011760
16,20260727,"[20260721, 20260722, 20260723, 20260724, 20260...","[20260721, 20260722, 20260723, 20260724, 20260...",[],"(300, 300)",0.009657
17,20260730,"[20260724, 20260727, 20260728, 20260729, 20260...","[20260724, 20260727, 20260728, 20260730]",[20260729],"(300, 300)",0.012947
18,20260731,"[20260727, 20260728, 20260729, 20260730, 20260...","[20260727, 20260728, 20260730, 20260731]",[20260729],"(300, 300)",0.014752

## Task6：按原流程逐日构建 basket1

In [21]:
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task6 "
        f"{run.construction_date}"
    )
    run.build_basket1()

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "basket1_invested_amount": (
                    run.basket1_invested_amount
                ),
                "basket1_held_stock_count": int(
                    (run.basket1["target_qty"] > 0).sum()
                ),
            }
            for run in date_runs
        ]
    )
)

[1/19] Task6 20260701
[pareto basket1] round=1, raw=1,694, local=63, materialized=63, frontier=63, beam=20, new=63, best_amount=0.17424769, best_TE=555.572522%
[pareto basket1] round=5, raw=37,873, local=741, materialized=736, frontier=105, beam=20, new=105, best_amount=0.16816950, best_TE=500.710978%
[pareto basket1] round=10, raw=28,274, local=563, materialized=553, frontier=102, beam=20, new=101, best_amount=0.16370712, best_TE=482.737040%
[pareto basket1] round=15, raw=23,955, local=384, materialized=364, frontier=113, beam=20, new=107, best_amount=0.16130604, best_TE=468.558171%
[pareto basket1] round=20, raw=16,262, local=301, materialized=295, frontier=117, beam=20, new=86, best_amount=0.15892463, best_TE=461.518452%
[pareto basket1] round=25, raw=14,850, local=281, materialized=267, frontier=181, beam=20, new=97, best_amount=0.15803714, best_TE=452.984629%
[pareto basket1] round=30, raw=10,689, local=255, materialized=234, frontier=138, beam=20, new=96, best_amount=0.15795575, best_TE=449.460903%
[pareto basket1] round=35, raw=12,671, local=305, materialized=288, frontier=250, beam=20, new=92, best_amount=0.15740998, best_TE=441.794752%
[pareto basket1] round=40, raw=11,865, local=305, materialized=292, frontier=264, beam=20, new=104, best_amount=0.15676700, best_TE=437.478553%
[pareto basket1] round=45, raw=11,923, local=291, materialized=274, frontier=294, beam=20, new=115, best_amount=0.15676700, best_TE=434.777367%
[pareto basket1] round=50, raw=11,668, local=248, materialized=232, frontier=362, beam=20, new=64, best_amount=0.15676700, best_TE=432.712335%
[2/19] Task6 20260702
[pareto basket1] round=1, raw=1,904, local=46, materialized=46, frontier=46, beam=20, new=46, best_amount=0.18031323, best_TE=576.176402%
[pareto basket1] round=5, raw=47,534, local=599, materialized=593, frontier=102, beam=20, new=102, best_amount=0.17284777, best_TE=495.199920%
[pareto basket1] round=10, raw=45,049, local=688, materialized=672, frontier=126, beam=20, new=83, best_amount=0.16684146, best_TE=461.726288%
[pareto basket1] round=15, raw=34,331, local=662, materialized=654, frontier=210, beam=20, new=208, best_amount=0.16340277, best_TE=448.307798%
[pareto basket1] round=20, raw=25,746, local=648, materialized=628, frontier=243, beam=20, new=197, best_amount=0.16072102, best_TE=437.667454%
[pareto basket1] round=25, raw=20,039, local=498, materialized=492, frontier=257, beam=20, new=171, best_amount=0.16007647, best_TE=432.533711%
[pareto basket1] round=30, raw=15,506, local=545, materialized=475, frontier=313, beam=20, new=138, best_amount=0.15993824, best_TE=428.097659%
[pareto basket1] round=35, raw=18,423, local=519, materialized=479, frontier=274, beam=20, new=123, best_amount=0.15928225, best_TE=428.097659%
[pareto basket1] round=40, raw=15,074, local=506, materialized=437, frontier=232, beam=20, new=88, best_amount=0.15899522, best_TE=428.097659%
[pareto basket1] round=45, raw=14,423, local=410, materialized=381, frontier=243, beam=20, new=80, best_amount=0.15843022, best_TE=427.957061%
[pareto basket1] round=50, raw=13,434, local=584, materialized=488, frontier=245, beam=20, new=104, best_amount=0.15774437, best_TE=427.780128%
[3/19] Task6 20260703
[pareto basket1] round=1, raw=2,027, local=39, materialized=39, frontier=39, beam=20, new=39, best_amount=0.17972259, best_TE=562.766636%
[pareto basket1] round=5, raw=51,067, local=720, materialized=683, frontier=160, beam=20, new=160, best_amount=0.17258416, best_TE=481.358908%
[pareto basket1] round=10, raw=42,505, local=671, materialized=666, frontier=143, beam=20, new=139, best_amount=0.16658485, best_TE=455.877346%
[pareto basket1] round=15, raw=42,315, local=689, materialized=670, frontier=201, beam=20, new=172, best_amount=0.16266539, best_TE=441.511034%
[pareto basket1] round=20, raw=32,267, local=678, materialized=671, frontier=359, beam=20, new=229, best_amount=0.16178928, best_TE=432.080764%
[pareto basket1] round=25, raw=28,399, local=598, materialized=559, frontier=365, beam=20, new=236, best_amount=0.16048139, best_TE=425.901182%
[pareto basket1] round=30, raw=24,193, local=619, materialized=594, frontier=332, beam=20, new=157, best_amount=0.15983631, best_TE=424.671257%
[pareto basket1] round=35, raw=20,111, local=581, materialized=556, frontier=293, beam=20, new=161, best_amount=0.15955711, best_TE=423.208482%
[pareto basket1] round=40, raw=12,923, local=356, materialized=328, frontier=280, beam=20, new=94, best_amount=0.15955711, best_TE=419.791243%
[pareto basket1] round=45, raw=13,775, local=436, materialized=387, frontier=360, beam=20, new=101, best_amount=0.15955711, best_TE=419.791243%
[pareto basket1] round=50, raw=12,112, local=437, materialized=403, frontier=347, beam=20, new=165, best_amount=0.15955711, best_TE=419.791243%
[4/19] Task6 20260706
[pareto basket1] round=1, raw=2,334, local=26, materialized=26, frontier=26, beam=20, new=26, best_amount=0.18012442, best_TE=567.254260%
[pareto basket1] round=5, raw=60,631, local=795, materialized=786, frontier=134, beam=20, new=134, best_amount=0.17307849, best_TE=480.662552%
[pareto basket1] round=10, raw=59,740, local=754, materialized=728, frontier=115, beam=20, new=84, best_amount=0.16654766, best_TE=456.385976%
[pareto basket1] round=15, raw=39,998, local=682, materialized=668, frontier=166, beam=20, new=156, best_amount=0.16383928, best_TE=439.859930%
[pareto basket1] round=20, raw=22,709, local=489, materialized=478, frontier=194, beam=20, new=158, best_amount=0.16219738, best_TE=429.242814%
[pareto basket1] round=25, raw=24,854, local=513, materialized=499, frontier=212, beam=20, new=120, best_amount=0.16129782, best_TE=425.611833%
[pareto basket1] round=30, raw=19,618, local=457, materialized=437, frontier=244, beam=20, new=167, best_amount=0.15872742, best_TE=421.346942%
[pareto basket1] round=35, raw=16,330, local=422, materialized=395, frontier=231, beam=20, new=145, best_amount=0.15778351, best_TE=416.188480%
[pareto basket1] round=40, raw=16,075, local=361, materialized=324, frontier=292, beam=20, new=118, best_amount=0.15746549, best_TE=412.522923%
[pareto basket1] round=45, raw=21,328, local=436, materialized=381, frontier=279, beam=20, new=68, best_amount=0.15692862, best_TE=411.937211%
[pareto basket1] round=50, raw=19,014, local=514, materialized=463, frontier=347, beam=20, new=168, best_amount=0.15656466, best_TE=411.098972%
[5/19] Task6 20260707
[pareto basket1] round=1, raw=2,012, local=33, materialized=33, frontier=33, beam=20, new=33, best_amount=0.17836176, best_TE=563.183484%
[pareto basket1] round=5, raw=61,157, local=815, materialized=803, frontier=95, beam=20, new=95, best_amount=0.17148088, best_TE=472.125963%
[pareto basket1] round=10, raw=47,737, local=771, materialized=765, frontier=137, beam=20, new=106, best_amount=0.16706445, best_TE=449.091020%
[pareto basket1] round=15, raw=49,180, local=943, materialized=935, frontier=198, beam=20, new=167, best_amount=0.16346694, best_TE=435.595189%
[pareto basket1] round=20, raw=44,154, local=857, materialized=852, frontier=233, beam=20, new=176, best_amount=0.16140649, best_TE=425.985032%
[pareto basket1] round=25, raw=27,064, local=585, materialized=582, frontier=256, beam=20, new=114, best_amount=0.16040695, best_TE=417.817755%
[pareto basket1] round=30, raw=32,215, local=729, materialized=690, frontier=360, beam=20, new=231, best_amount=0.15899107, best_TE=413.927769%
[pareto basket1] round=35, raw=28,914, local=759, materialized=714, frontier=525, beam=20, new=258, best_amount=0.15847226, best_TE=413.409287%
[pareto basket1] round=40, raw=25,740, local=577, materialized=538, frontier=451, beam=20, new=121, best_amount=0.15820191, best_TE=413.409287%
[pareto basket1] round=45, raw=28,665, local=756, materialized=676, frontier=474, beam=20, new=244, best_amount=0.15817840, best_TE=413.409287%
[pareto basket1] round=50, raw=17,825, local=726, materialized=695, frontier=426, beam=20, new=141, best_amount=0.15817840, best_TE=413.409287%
[6/19] Task6 20260708
[pareto basket1] round=1, raw=1,934, local=40, materialized=40, frontier=40, beam=20, new=40, best_amount=0.17576714, best_TE=556.677230%
[pareto basket1] round=5, raw=57,159, local=966, materialized=957, frontier=116, beam=20, new=116, best_amount=0.17039223, best_TE=455.528528%
[pareto basket1] round=10, raw=55,777, local=713, materialized=700, frontier=126, beam=20, new=73, best_amount=0.16463358, best_TE=429.234534%
[pareto basket1] round=15, raw=42,498, local=863, materialized=831, frontier=205, beam=20, new=101, best_amount=0.16171580, best_TE=418.147716%
[pareto basket1] round=20, raw=25,831, local=770, materialized=756, frontier=189, beam=20, new=161, best_amount=0.16048003, best_TE=411.785804%
[pareto basket1] round=25, raw=23,029, local=697, materialized=670, frontier=287, beam=20, new=198, best_amount=0.16004190, best_TE=406.613508%
[pareto basket1] round=30, raw=20,607, local=534, materialized=507, frontier=351, beam=20, new=159, best_amount=0.15970565, best_TE=399.271804%
[pareto basket1] round=35, raw=20,577, local=545, materialized=508, frontier=342, beam=20, new=142, best_amount=0.15970565, best_TE=397.087548%
[pareto basket1] round=40, raw=22,167, local=593, materialized=545, frontier=355, beam=20, new=151, best_amount=0.15941096, best_TE=394.300908%
[pareto basket1] round=45, raw=19,666, local=586, materialized=508, frontier=366, beam=20, new=147, best_amount=0.15933696, best_TE=394.300908%
[pareto basket1] round=50, raw=18,231, local=558, materialized=460, frontier=359, beam=20, new=109, best_amount=0.15932416, best_TE=394.061419%
[7/19] Task6 20260709
[pareto basket1] round=1, raw=2,329, local=14, materialized=14, frontier=14, beam=14, new=14, best_amount=0.18223664, best_TE=544.669586%
[pareto basket1] round=5, raw=56,674, local=758, materialized=752, frontier=93, beam=20, new=93, best_amount=0.17451740, best_TE=480.605438%
[pareto basket1] round=10, raw=40,511, local=682, materialized=679, frontier=120, beam=20, new=108, best_amount=0.16886423, best_TE=459.877460%
[pareto basket1] round=15, raw=36,694, local=619, materialized=612, frontier=169, beam=20, new=102, best_amount=0.16575412, best_TE=451.874028%
[pareto basket1] round=20, raw=25,561, local=471, materialized=465, frontier=170, beam=20, new=142, best_amount=0.16398535, best_TE=444.093397%
[pareto basket1] round=25, raw=19,789, local=562, materialized=538, frontier=242, beam=20, new=176, best_amount=0.16275401, best_TE=439.828669%
[pareto basket1] round=30, raw=21,402, local=566, materialized=496, frontier=321, beam=20, new=130, best_amount=0.16215075, best_TE=434.808517%
[pareto basket1] round=35, raw=16,930, local=447, materialized=421, frontier=354, beam=20, new=123, best_amount=0.16215075, best_TE=431.900074%
[pareto basket1] round=40, raw=10,440, local=322, materialized=303, frontier=413, beam=20, new=137, best_amount=0.16215075, best_TE=431.502740%
[pareto basket1] round=45, raw=10,686, local=358, materialized=351, frontier=355, beam=20, new=128, best_amount=0.16215075, best_TE=431.502740%
[pareto basket1] round=50, raw=13,371, local=542, materialized=504, frontier=424, beam=20, new=153, best_amount=0.16215075, best_TE=429.399842%
[8/19] Task6 20260710
[pareto basket1] round=1, raw=1,890, local=23, materialized=23, frontier=23, beam=20, new=23, best_amount=0.17416816, best_TE=543.296328%
[pareto basket1] round=5, raw=58,823, local=524, materialized=516, frontier=63, beam=20, new=63, best_amount=0.16723651, best_TE=458.144117%
[pareto basket1] round=10, raw=48,763, local=629, materialized=623, frontier=135, beam=20, new=131, best_amount=0.16165180, best_TE=437.554950%
[pareto basket1] round=15, raw=31,661, local=444, materialized=433, frontier=114, beam=20, new=103, best_amount=0.16052241, best_TE=426.822486%
[pareto basket1] round=20, raw=25,849, local=318, materialized=306, frontier=148, beam=20, new=107, best_amount=0.15876583, best_TE=419.951063%
[pareto basket1] round=25, raw=17,862, local=298, materialized=287, frontier=181, beam=20, new=92, best_amount=0.15766072, best_TE=415.803972%
[pareto basket1] round=30, raw=14,208, local=344, materialized=324, frontier=198, beam=20, new=117, best_amount=0.15720392, best_TE=411.224974%
[pareto basket1] round=35, raw=12,875, local=320, materialized=281, frontier=267, beam=20, new=118, best_amount=0.15720392, best_TE=408.516471%
[pareto basket1] round=40, raw=12,893, local=241, materialized=208, frontier=308, beam=20, new=71, best_amount=0.15720392, best_TE=406.331476%
[pareto basket1] round=45, raw=9,310, local=301, materialized=290, frontier=346, beam=20, new=120, best_amount=0.15720392, best_TE=406.307544%
[pareto basket1] round=50, raw=9,217, local=227, materialized=222, frontier=344, beam=20, new=58, best_amount=0.15720392, best_TE=405.182380%
[9/19] Task6 20260713
[pareto basket1] round=1, raw=1,787, local=53, materialized=53, frontier=53, beam=20, new=53, best_amount=0.16789316, best_TE=546.857393%
[pareto basket1] round=5, raw=55,420, local=627, materialized=609, frontier=100, beam=20, new=100, best_amount=0.16207292, best_TE=438.176531%
[pareto basket1] round=10, raw=53,357, local=920, materialized=888, frontier=202, beam=20, new=140, best_amount=0.15873660, best_TE=409.538023%
[pareto basket1] round=15, raw=39,482, local=839, materialized=834, frontier=216, beam=20, new=205, best_amount=0.15699370, best_TE=397.693163%
[pareto basket1] round=20, raw=42,520, local=703, materialized=692, frontier=320, beam=20, new=172, best_amount=0.15544731, best_TE=388.107243%
[pareto basket1] round=25, raw=29,720, local=577, materialized=565, frontier=411, beam=20, new=122, best_amount=0.15459941, best_TE=384.774747%
[pareto basket1] round=30, raw=25,043, local=538, materialized=497, frontier=441, beam=20, new=165, best_amount=0.15432183, best_TE=380.676612%
[pareto basket1] round=35, raw=29,973, local=554, materialized=516, frontier=440, beam=20, new=164, best_amount=0.15341034, best_TE=377.578771%
[pareto basket1] round=40, raw=22,019, local=522, materialized=495, frontier=437, beam=20, new=162, best_amount=0.15320611, best_TE=375.138111%
[pareto basket1] round=45, raw=16,639, local=483, materialized=458, frontier=526, beam=20, new=176, best_amount=0.15320611, best_TE=374.249959%
[pareto basket1] round=50, raw=13,598, local=337, materialized=313, frontier=564, beam=20, new=131, best_amount=0.15320611, best_TE=372.684270%
[10/19] Task6 20260714
[pareto basket1] round=1, raw=2,030, local=52, materialized=52, frontier=52, beam=20, new=52, best_amount=0.17743794, best_TE=524.698098%
[pareto basket1] round=5, raw=63,954, local=724, materialized=709, frontier=82, beam=20, new=82, best_amount=0.17058252, best_TE=420.232148%
[pareto basket1] round=10, raw=44,479, local=723, materialized=719, frontier=163, beam=20, new=163, best_amount=0.16574786, best_TE=396.438967%
[pareto basket1] round=15, raw=29,790, local=665, materialized=661, frontier=207, beam=20, new=206, best_amount=0.16246987, best_TE=385.218768%
[pareto basket1] round=20, raw=26,490, local=667, materialized=652, frontier=246, beam=20, new=192, best_amount=0.16026940, best_TE=376.844704%
[pareto basket1] round=25, raw=18,891, local=464, materialized=446, frontier=240, beam=20, new=189, best_amount=0.15966987, best_TE=370.694161%
[pareto basket1] round=30, raw=20,836, local=446, materialized=432, frontier=274, beam=20, new=172, best_amount=0.15842026, best_TE=365.414170%
[pareto basket1] round=35, raw=19,103, local=394, materialized=366, frontier=364, beam=20, new=162, best_amount=0.15842026, best_TE=362.408481%
[pareto basket1] round=40, raw=13,998, local=352, materialized=319, frontier=288, beam=20, new=97, best_amount=0.15838926, best_TE=358.910315%
[pareto basket1] round=45, raw=16,426, local=336, materialized=329, frontier=401, beam=20, new=106, best_amount=0.15829263, best_TE=358.474432%
[pareto basket1] round=50, raw=18,846, local=487, materialized=456, frontier=479, beam=20, new=169, best_amount=0.15829263, best_TE=358.474432%
[11/19] Task6 20260715
[pareto basket1] round=1, raw=2,836, local=41, materialized=41, frontier=41, beam=20, new=41, best_amount=0.17166262, best_TE=514.927009%
[pareto basket1] round=5, raw=61,239, local=710, materialized=695, frontier=86, beam=20, new=86, best_amount=0.16462606, best_TE=391.622403%
[pareto basket1] round=10, raw=51,414, local=658, materialized=644, frontier=154, beam=20, new=124, best_amount=0.15890979, best_TE=368.932335%
[pareto basket1] round=15, raw=38,751, local=587, materialized=581, frontier=171, beam=20, new=141, best_amount=0.15608721, best_TE=355.708552%
[pareto basket1] round=20, raw=34,910, local=997, materialized=970, frontier=309, beam=20, new=227, best_amount=0.15605127, best_TE=350.592426%
[pareto basket1] round=25, raw=25,270, local=636, materialized=621, frontier=361, beam=20, new=205, best_amount=0.15605127, best_TE=345.909116%
[pareto basket1] round=30, raw=15,161, local=436, materialized=422, frontier=360, beam=20, new=144, best_amount=0.15605127, best_TE=342.049724%
[pareto basket1] round=35, raw=18,799, local=532, materialized=519, frontier=310, beam=20, new=131, best_amount=0.15605127, best_TE=338.068951%
[pareto basket1] round=40, raw=17,086, local=515, materialized=467, frontier=436, beam=20, new=97, best_amount=0.15605127, best_TE=336.034893%
[pareto basket1] round=45, raw=13,342, local=322, materialized=314, frontier=365, beam=20, new=112, best_amount=0.15605127, best_TE=335.390398%
[pareto basket1] round=50, raw=13,634, local=238, materialized=228, frontier=226, beam=20, new=70, best_amount=0.15572944, best_TE=335.370444%
[12/19] Task6 20260716
[pareto basket1] round=1, raw=2,224, local=59, materialized=59, frontier=59, beam=20, new=59, best_amount=0.16246446, best_TE=512.348555%
[pareto basket1] round=5, raw=57,076, local=778, materialized=774, frontier=99, beam=20, new=99, best_amount=0.15713729, best_TE=375.624003%
[pareto basket1] round=10, raw=40,041, local=637, materialized=629, frontier=178, beam=20, new=174, best_amount=0.15366863, best_TE=352.420812%
[pareto basket1] round=15, raw=46,967, local=809, materialized=749, frontier=247, beam=20, new=138, best_amount=0.15161004, best_TE=340.519074%
[pareto basket1] round=20, raw=40,987, local=732, materialized=708, frontier=279, beam=20, new=192, best_amount=0.15072438, best_TE=333.834581%
[pareto basket1] round=25, raw=26,808, local=470, materialized=456, frontier=201, beam=20, new=148, best_amount=0.14950042, best_TE=329.611573%
[pareto basket1] round=30, raw=20,653, local=393, materialized=387, frontier=214, beam=20, new=127, best_amount=0.14936060, best_TE=329.266345%
[pareto basket1] round=35, raw=23,742, local=401, materialized=395, frontier=292, beam=20, new=133, best_amount=0.14927484, best_TE=328.333394%
[pareto basket1] round=40, raw=17,120, local=291, materialized=288, frontier=359, beam=20, new=70, best_amount=0.14927484, best_TE=324.105738%
[pareto basket1] round=45, raw=16,191, local=315, materialized=311, frontier=396, beam=20, new=145, best_amount=0.14927484, best_TE=323.898265%
[pareto basket1] round=50, raw=14,028, local=224, materialized=215, frontier=342, beam=20, new=85, best_amount=0.14927484, best_TE=323.442551%
[13/19] Task6 20260721
[pareto basket1] round=1, raw=2,121, local=80, materialized=80, frontier=80, beam=20, new=80, best_amount=0.16708965, best_TE=545.388136%
[pareto basket1] round=5, raw=54,014, local=855, materialized=843, frontier=80, beam=20, new=80, best_amount=0.16164434, best_TE=406.843570%
[pareto basket1] round=10, raw=44,534, local=789, materialized=784, frontier=125, beam=20, new=124, best_amount=0.15618889, best_TE=377.294322%
[pareto basket1] round=15, raw=34,030, local=616, materialized=614, frontier=249, beam=20, new=232, best_amount=0.15454321, best_TE=360.653711%
[pareto basket1] round=20, raw=33,378, local=494, materialized=478, frontier=245, beam=20, new=147, best_amount=0.15233911, best_TE=351.384648%

   construction_date  basket1_invested_amount  basket1_held_stock_count
0           20260701               4514954.90                       274
1           20260702               4514452.07                       278
2           20260703               4509257.47                       281
3           20260706               4519512.45                       281
4           20260707               4518819.08                       277
5           20260708               4500072.13                       277
6           20260709               4521931.72                       282
7           20260710               4517055.81                       282
8           20260713               4500084.89                       281
9           20260714               4505582.12                       281
10          20260715               4503950.22                       278
11          20260716               4500117.63                       279
12          20260721               4513863.04                       281
13          20260722               4512848.20                       282
14          20260723               4512487.11                       281
15          20260724               4504833.10                       284
16          20260727               4520988.49                       283
17          20260730               4520274.11                       281
18          20260731               4519385.68                       281

## Task7：逐日读取 D+1 09:31 价格与迅投涨跌停/停牌状态

In [22]:
late_unavailable_dates = set()
status_ready_runs = []
for position, run in enumerate(date_runs, start=1):
    if set(run.transition_dates) & late_unavailable_dates:
        continue
    print(
        f"[{position}/{len(date_runs)}] Task7 "
        f"{run.construction_date} -> {run.evaluation_date}"
    )
    if run.load_d1_status():
        status_ready_runs.append(run)
    else:
        late_unavailable_dates.add(run.evaluation_date)

date_runs = filter_available_date_runs(
    status_ready_runs, late_unavailable_dates
)
construction_date_ls = [run.construction_date for run in date_runs]
if not date_runs:
    raise RuntimeError("D+1 状态检查后没有可计算区间。")

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "evaluation_date": run.evaluation_date,
                "unavailable_component_count": len(
                    run.status_unavailable_codes
                ),
                "manual_not_in_universe": (
                    run.manual_not_in_universe
                ),
            }
            for run in date_runs
        ]
    )
)

[1/19] Task7 20260701 -> 20260702
[CACHE HIT] D+1 opening cache 20260701 20260702: basket_minute_wide_20260702_ea54ee2142d4.pkl (3.99 MB)
[2/19] Task7 20260702 -> 20260703
[CACHE HIT] D+1 opening cache 20260702 20260703: basket_minute_wide_20260703_bfa50f229284.pkl (3.99 MB)
[3/19] Task7 20260703 -> 20260706
[CACHE HIT] D+1 opening cache 20260703 20260706: basket_minute_wide_20260706_b0ca6a949f2e.pkl (3.99 MB)
[4/19] Task7 20260706 -> 20260707
[CACHE HIT] D+1 opening cache 20260706 20260707: basket_minute_wide_20260707_14ca0077a818.pkl (3.99 MB)
[5/19] Task7 20260707 -> 20260708
[CACHE HIT] D+1 opening cache 20260707 20260708: basket_minute_wide_20260708_828a77b111aa.pkl (3.99 MB)
[6/19] Task7 20260708 -> 20260709
[CACHE HIT] D+1 opening cache 20260708 20260709: basket_minute_wide_20260709_a7ccd4bdc8b1.pkl (3.99 MB)
[7/19] Task7 20260709 -> 20260710
[CACHE HIT] D+1 opening cache 20260709 20260710: basket_minute_wide_20260710_7c4ba95815ad.pkl (3.99 MB)
[8/19] Task7 20260710 -> 20260713
[CACHE HIT] D+1 opening cache 20260710 20260713: basket_minute_wide_20260713_c4ba869aeaa3.pkl (3.99 MB)
[9/19] Task7 20260713 -> 20260714
[CACHE HIT] D+1 opening cache 20260713 20260714: basket_minute_wide_20260714_55602bf344ce.pkl (3.99 MB)
[10/19] Task7 20260714 -> 20260715
[CACHE HIT] D+1 opening cache 20260714 20260715: basket_minute_wide_20260715_cae63993f1ac.pkl (3.99 MB)
[11/19] Task7 20260715 -> 20260716
[CACHE HIT] D+1 opening cache 20260715 20260716: basket_minute_wide_20260716_8f3e40ee0225.pkl (3.99 MB)
[12/19] Task7 20260716 -> 20260717
[CACHE HIT] D+1 opening cache 20260716 20260717: basket_minute_wide_20260717_c859066a4831.pkl (3.99 MB)
[13/19] Task7 20260721 -> 20260722
[CACHE HIT] D+1 opening cache 20260721 20260722: basket_minute_wide_20260722_59d090e010f1.pkl (3.99 MB)
[14/19] Task7 20260722 -> 20260723
[CACHE HIT] D+1 opening cache 20260722 20260723: basket_minute_wide_20260723_eb79c936a2ed.pkl (3.99 MB)
[15/19] Task7 20260723 -> 20260724
[CACHE HIT] D+1 opening cache 20260723 20260724: basket_minute_wide_20260724_9f6d4e0ecd07.pkl (3.99 MB)
[16/19] Task7 20260724 -> 20260727
[CACHE HIT] D+1 opening cache 20260724 20260727: basket_minute_wide_20260727_f5356c5f686c.pkl (3.99 MB)
[17/19] Task7 20260727 -> 20260728
[CACHE HIT] D+1 opening cache 20260727 20260728: basket_minute_wide_20260728_e46fb5fdcd27.pkl (3.99 MB)
[18/19] Task7 20260730 -> 20260731
[CACHE HIT] D+1 opening cache 20260730 20260731: basket_minute_wide_20260731_2db8329b6633.pkl (3.99 MB)
[19/19] Task7 20260731 -> 20260803
[CACHE HIT] D+1 opening cache 20260731 20260803: basket_minute_wide_20260803_19aecbe3042d.pkl (3.99 MB)

,construction_date,evaluation_date,unavailable_component_count,manual_not_in_universe
0,20260701,20260702,2,[]
1,20260702,20260703,3,[]
2,20260703,20260706,2,[]
3,20260706,20260707,2,[]
4,20260707,20260708,5,[]
5,20260708,20260709,2,[]
6,20260709,20260710,2,[]
7,20260710,20260713,1,[]
8,20260713,20260714,1,[]
9,20260714,20260715,1,[]
10,20260715,20260716,1,[]
11,20260716,20260717,1,[]
12,20260721,20260722,1,[]
13,20260722,20260723,2,[]
14,20260723,20260724,1,[]
15,20260724,20260727,1,[]
16,20260727,20260728,1,[]
17,20260730,20260731,3,[]
18,20260731,20260803,1,[]

## Task8：逐日在全部成分股中排除不可买后重新拟合 basket3

In [23]:
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task8 "
        f"{run.construction_date}"
    )
    run.build_basket3()

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "basket3_invested_amount": run.basket3[
                    "target_market_value"
                ].sum(),
                "basket3_held_stock_count": int(
                    (run.basket3["target_qty"] > 0).sum()
                ),
                "excluded_component_count": len(
                    run.all_unavailable_codes
                ),
            }
            for run in date_runs
        ]
    )
)

[1/19] Task8 20260701
[pareto basket3] round=1, raw=1,955, local=68, materialized=68, frontier=68, beam=20, new=68, best_amount=0.18098229, best_TE=562.473602%
[pareto basket3] round=5, raw=43,385, local=760, materialized=748, frontier=95, beam=20, new=95, best_amount=0.17433378, best_TE=500.809160%
[pareto basket3] round=10, raw=26,967, local=451, materialized=447, frontier=114, beam=20, new=91, best_amount=0.16941284, best_TE=481.524393%
[pareto basket3] round=15, raw=21,871, local=332, materialized=307, frontier=97, beam=20, new=73, best_amount=0.16661823, best_TE=468.944677%
[pareto basket3] round=20, raw=17,345, local=328, materialized=306, frontier=159, beam=20, new=115, best_amount=0.16400146, best_TE=458.635457%
[pareto basket3] round=25, raw=17,820, local=389, materialized=364, frontier=184, beam=20, new=99, best_amount=0.16324194, best_TE=449.979047%
[pareto basket3] round=30, raw=17,204, local=352, materialized=323, frontier=210, beam=20, new=139, best_amount=0.16321414, best_TE=446.555019%
[pareto basket3] round=35, raw=12,806, local=325, materialized=294, frontier=310, beam=20, new=125, best_amount=0.16257898, best_TE=440.322218%
[pareto basket3] round=40, raw=11,113, local=353, materialized=322, frontier=323, beam=20, new=119, best_amount=0.16217176, best_TE=436.769812%
[pareto basket3] round=45, raw=10,527, local=272, materialized=240, frontier=368, beam=20, new=87, best_amount=0.16217176, best_TE=436.600884%
[pareto basket3] round=50, raw=12,357, local=319, materialized=279, frontier=448, beam=20, new=88, best_amount=0.16217176, best_TE=435.107358%
[2/19] Task8 20260702
[pareto basket3] round=1, raw=2,625, local=36, materialized=36, frontier=36, beam=20, new=36, best_amount=0.18198766, best_TE=573.794572%
[pareto basket3] round=5, raw=51,232, local=686, materialized=672, frontier=141, beam=20, new=141, best_amount=0.17478978, best_TE=489.934692%
[pareto basket3] round=10, raw=39,365, local=563, materialized=559, frontier=100, beam=20, new=100, best_amount=0.16827016, best_TE=457.821273%
[pareto basket3] round=15, raw=26,545, local=584, materialized=568, frontier=111, beam=20, new=105, best_amount=0.16425375, best_TE=448.581238%
[pareto basket3] round=20, raw=17,368, local=422, materialized=406, frontier=188, beam=20, new=140, best_amount=0.16412629, best_TE=441.223725%
[pareto basket3] round=25, raw=16,145, local=451, materialized=424, frontier=254, beam=20, new=118, best_amount=0.16384542, best_TE=437.152659%
[pareto basket3] round=30, raw=20,659, local=395, materialized=364, frontier=265, beam=20, new=145, best_amount=0.16244441, best_TE=430.050565%
[pareto basket3] round=35, raw=16,060, local=541, materialized=508, frontier=384, beam=20, new=224, best_amount=0.16203212, best_TE=428.697390%
[pareto basket3] round=40, raw=16,329, local=525, materialized=504, frontier=291, beam=20, new=138, best_amount=0.16178654, best_TE=428.697390%
[pareto basket3] round=45, raw=16,183, local=530, materialized=498, frontier=358, beam=20, new=165, best_amount=0.16174463, best_TE=428.256523%
[pareto basket3] round=50, raw=12,772, local=431, materialized=411, frontier=409, beam=20, new=158, best_amount=0.16142770, best_TE=424.217606%
[3/19] Task8 20260703
[pareto basket3] round=1, raw=2,664, local=44, materialized=44, frontier=44, beam=20, new=44, best_amount=0.18163022, best_TE=558.706729%
[pareto basket3] round=5, raw=47,263, local=611, materialized=596, frontier=129, beam=20, new=129, best_amount=0.17416557, best_TE=473.800827%
[pareto basket3] round=10, raw=27,538, local=486, materialized=479, frontier=124, beam=20, new=124, best_amount=0.16777867, best_TE=454.252198%
[pareto basket3] round=15, raw=22,706, local=606, materialized=552, frontier=204, beam=20, new=164, best_amount=0.16410039, best_TE=442.689610%
[pareto basket3] round=20, raw=17,610, local=511, materialized=503, frontier=218, beam=20, new=148, best_amount=0.16384208, best_TE=434.184015%
[pareto basket3] round=25, raw=16,494, local=528, materialized=495, frontier=309, beam=20, new=189, best_amount=0.16308070, best_TE=428.537106%
[pareto basket3] round=30, raw=17,657, local=518, materialized=495, frontier=422, beam=20, new=154, best_amount=0.16271742, best_TE=423.067537%
[pareto basket3] round=35, raw=13,307, local=458, materialized=438, frontier=458, beam=20, new=137, best_amount=0.16266475, best_TE=421.248315%
[pareto basket3] round=40, raw=13,781, local=554, materialized=519, frontier=552, beam=20, new=190, best_amount=0.16259150, best_TE=416.889131%
[pareto basket3] round=45, raw=15,062, local=623, materialized=531, frontier=555, beam=20, new=149, best_amount=0.16253176, best_TE=412.910113%
[pareto basket3] round=50, raw=13,477, local=413, materialized=324, frontier=492, beam=20, new=117, best_amount=0.16208801, best_TE=409.711920%
[4/19] Task8 20260706
[pareto basket3] round=1, raw=2,482, local=27, materialized=27, frontier=27, beam=20, new=27, best_amount=0.18254279, best_TE=565.390750%
[pareto basket3] round=5, raw=50,696, local=654, materialized=629, frontier=90, beam=20, new=90, best_amount=0.17484703, best_TE=475.824875%
[pareto basket3] round=10, raw=39,100, local=631, materialized=623, frontier=160, beam=20, new=160, best_amount=0.16932717, best_TE=454.690818%
[pareto basket3] round=15, raw=30,967, local=550, materialized=531, frontier=162, beam=20, new=143, best_amount=0.16537159, best_TE=442.131674%
[pareto basket3] round=20, raw=17,552, local=476, materialized=461, frontier=233, beam=20, new=143, best_amount=0.16396597, best_TE=432.168421%
[pareto basket3] round=25, raw=15,247, local=426, materialized=403, frontier=244, beam=20, new=139, best_amount=0.16361848, best_TE=423.002953%
[pareto basket3] round=30, raw=20,452, local=587, materialized=555, frontier=413, beam=20, new=183, best_amount=0.16310960, best_TE=417.875389%
[pareto basket3] round=35, raw=22,030, local=670, materialized=657, frontier=412, beam=20, new=220, best_amount=0.16247048, best_TE=414.459346%
[pareto basket3] round=40, raw=15,637, local=495, materialized=479, frontier=403, beam=20, new=167, best_amount=0.16185394, best_TE=409.970275%
[pareto basket3] round=45, raw=16,822, local=666, materialized=636, frontier=518, beam=20, new=310, best_amount=0.16180411, best_TE=407.544041%
[pareto basket3] round=50, raw=14,577, local=475, materialized=451, frontier=501, beam=20, new=208, best_amount=0.16130879, best_TE=405.570408%
[5/19] Task8 20260707
[pareto basket3] round=1, raw=2,664, local=39, materialized=39, frontier=39, beam=20, new=39, best_amount=0.19256037, best_TE=619.018169%
[pareto basket3] round=5, raw=76,726, local=865, materialized=825, frontier=107, beam=20, new=107, best_amount=0.18574740, best_TE=490.290795%
[pareto basket3] round=10, raw=56,277, local=648, materialized=646, frontier=130, beam=20, new=127, best_amount=0.17952948, best_TE=457.879281%
[pareto basket3] round=15, raw=32,496, local=536, materialized=532, frontier=188, beam=20, new=148, best_amount=0.17712188, best_TE=446.178787%
[pareto basket3] round=20, raw=28,879, local=406, materialized=392, frontier=173, beam=20, new=91, best_amount=0.17502711, best_TE=438.100023%
[pareto basket3] round=25, raw=21,622, local=432, materialized=390, frontier=236, beam=20, new=159, best_amount=0.17410394, best_TE=432.561721%
[pareto basket3] round=30, raw=26,941, local=512, materialized=469, frontier=301, beam=20, new=130, best_amount=0.17315520, best_TE=428.344837%
[pareto basket3] round=35, raw=19,410, local=381, materialized=361, frontier=273, beam=20, new=145, best_amount=0.17312072, best_TE=427.292469%
[pareto basket3] round=40, raw=18,748, local=398, materialized=373, frontier=266, beam=20, new=118, best_amount=0.17253256, best_TE=425.886770%
[pareto basket3] round=45, raw=18,878, local=434, materialized=399, frontier=290, beam=20, new=112, best_amount=0.17231947, best_TE=424.657646%
[pareto basket3] round=50, raw=17,954, local=394, materialized=357, frontier=304, beam=20, new=95, best_amount=0.17217235, best_TE=421.373738%
[6/19] Task8 20260708
[pareto basket3] round=1, raw=2,061, local=38, materialized=38, frontier=38, beam=20, new=38, best_amount=0.17734126, best_TE=540.464382%
[pareto basket3] round=5, raw=67,819, local=843, materialized=830, frontier=95, beam=20, new=95, best_amount=0.17141807, best_TE=448.952184%
[pareto basket3] round=10, raw=49,856, local=715, materialized=694, frontier=141, beam=20, new=123, best_amount=0.16652822, best_TE=428.679320%
[pareto basket3] round=15, raw=35,041, local=520, materialized=514, frontier=201, beam=20, new=125, best_amount=0.16458701, best_TE=415.702898%
[pareto basket3] round=20, raw=27,382, local=639, materialized=618, frontier=262, beam=20, new=210, best_amount=0.16209524, best_TE=410.144166%
[pareto basket3] round=25, raw=21,352, local=567, materialized=558, frontier=346, beam=20, new=222, best_amount=0.16162646, best_TE=404.933447%
[pareto basket3] round=30, raw=17,027, local=527, materialized=519, frontier=404, beam=20, new=235, best_amount=0.16162646, best_TE=399.272748%
[pareto basket3] round=35, raw=19,922, local=482, materialized=447, frontier=477, beam=20, new=114, best_amount=0.16162646, best_TE=397.232677%
[pareto basket3] round=40, raw=17,286, local=439, materialized=396, frontier=485, beam=20, new=117, best_amount=0.16162646, best_TE=395.374039%
[pareto basket3] round=45, raw=15,276, local=374, materialized=361, frontier=499, beam=20, new=102, best_amount=0.16154368, best_TE=393.761626%
[pareto basket3] round=50, raw=16,961, local=497, materialized=472, frontier=538, beam=20, new=128, best_amount=0.16154368, best_TE=390.640047%
[7/19] Task8 20260709
[pareto basket3] round=1, raw=2,482, local=24, materialized=24, frontier=24, beam=20, new=24, best_amount=0.18893570, best_TE=535.231802%
[pareto basket3] round=5, raw=56,632, local=694, materialized=690, frontier=77, beam=20, new=77, best_amount=0.18121646, best_TE=482.239488%
[pareto basket3] round=10, raw=57,086, local=694, materialized=671, frontier=124, beam=20, new=97, best_amount=0.17568165, best_TE=462.393631%
[pareto basket3] round=15, raw=36,642, local=520, materialized=489, frontier=140, beam=20, new=116, best_amount=0.17193876, best_TE=451.750103%
[pareto basket3] round=20, raw=22,994, local=472, materialized=422, frontier=159, beam=20, new=91, best_amount=0.17022042, best_TE=448.456449%
[pareto basket3] round=25, raw=18,182, local=380, materialized=355, frontier=256, beam=20, new=134, best_amount=0.17010025, best_TE=444.506416%
[pareto basket3] round=30, raw=19,006, local=337, materialized=329, frontier=262, beam=20, new=75, best_amount=0.16907734, best_TE=440.640273%
[pareto basket3] round=35, raw=18,220, local=447, materialized=408, frontier=305, beam=20, new=149, best_amount=0.16892778, best_TE=436.591890%
[pareto basket3] round=40, raw=18,061, local=478, materialized=452, frontier=424, beam=20, new=134, best_amount=0.16889647, best_TE=433.737441%
[pareto basket3] round=45, raw=14,501, local=509, materialized=475, frontier=624, beam=20, new=203, best_amount=0.16889647, best_TE=428.375258%
[pareto basket3] round=50, raw=14,128, local=452, materialized=436, frontier=478, beam=20, new=180, best_amount=0.16889647, best_TE=425.760726%
[8/19] Task8 20260710
[pareto basket3] round=1, raw=1,940, local=21, materialized=21, frontier=21, beam=20, new=21, best_amount=0.18110096, best_TE=540.935986%
[pareto basket3] round=5, raw=52,999, local=572, materialized=563, frontier=66, beam=20, new=66, best_amount=0.17389999, best_TE=463.084346%
[pareto basket3] round=10, raw=46,409, local=593, materialized=589, frontier=136, beam=20, new=106, best_amount=0.16834218, best_TE=440.061776%
[pareto basket3] round=15, raw=33,246, local=591, materialized=575, frontier=192, beam=20, new=165, best_amount=0.16549610, best_TE=432.055539%
[pareto basket3] round=20, raw=23,606, local=491, materialized=473, frontier=246, beam=20, new=168, best_amount=0.16437351, best_TE=422.447413%
[pareto basket3] round=25, raw=16,193, local=366, materialized=339, frontier=241, beam=20, new=141, best_amount=0.16371981, best_TE=418.275994%
[pareto basket3] round=30, raw=15,916, local=366, materialized=326, frontier=305, beam=20, new=98, best_amount=0.16301927, best_TE=414.926771%
[pareto basket3] round=35, raw=11,905, local=273, materialized=263, frontier=363, beam=20, new=92, best_amount=0.16301927, best_TE=413.442736%
[pareto basket3] round=40, raw=9,310, local=220, materialized=196, frontier=346, beam=20, new=63, best_amount=0.16301927, best_TE=413.442736%
[pareto basket3] round=45, raw=11,494, local=279, materialized=268, frontier=314, beam=20, new=91, best_amount=0.16301927, best_TE=413.442736%
[pareto basket3] round=50, raw=13,242, local=364, materialized=338, frontier=292, beam=20, new=100, best_amount=0.16301927, best_TE=412.493857%
[9/19] Task8 20260713
[pareto basket3] round=1, raw=1,766, local=45, materialized=45, frontier=45, beam=20, new=45, best_amount=0.17466964, best_TE=543.322658%
[pareto basket3] round=5, raw=61,989, local=857, materialized=833, frontier=98, beam=20, new=98, best_amount=0.16815912, best_TE=442.169694%
[pareto basket3] round=10, raw=49,500, local=805, materialized=773, frontier=258, beam=20, new=239, best_amount=0.16468156, best_TE=415.372308%
[pareto basket3] round=15, raw=33,730, local=454, materialized=442, frontier=212, beam=20, new=140, best_amount=0.16257666, best_TE=404.239812%
[pareto basket3] round=20, raw=30,612, local=575, materialized=561, frontier=291, beam=20, new=204, best_amount=0.16031180, best_TE=396.895893%
[pareto basket3] round=25, raw=29,477, local=486, materialized=448, frontier=282, beam=20, new=98, best_amount=0.15899526, best_TE=389.917020%
[pareto basket3] round=30, raw=28,060, local=465, materialized=439, frontier=329, beam=20, new=113, best_amount=0.15809214, best_TE=382.657862%
[pareto basket3] round=35, raw=27,097, local=362, materialized=318, frontier=374, beam=20, new=102, best_amount=0.15759687, best_TE=377.815762%
[pareto basket3] round=40, raw=15,931, local=338, materialized=321, frontier=363, beam=20, new=118, best_amount=0.15759687, best_TE=376.610253%
[pareto basket3] round=45, raw=18,768, local=635, materialized=607, frontier=441, beam=20, new=192, best_amount=0.15741562, best_TE=376.166022%
[pareto basket3] round=50, raw=13,635, local=364, materialized=347, frontier=403, beam=20, new=117, best_amount=0.15722446, best_TE=376.166022%
[10/19] Task8 20260714
[pareto basket3] round=1, raw=2,394, local=35, materialized=35, frontier=35, beam=20, new=35, best_amount=0.17959140, best_TE=514.816846%
[pareto basket3] round=5, raw=58,438, local=541, materialized=534, frontier=65, beam=20, new=65, best_amount=0.17255362, best_TE=420.894941%
[pareto basket3] round=10, raw=38,022, local=571, materialized=562, frontier=96, beam=20, new=91, best_amount=0.16651493, best_TE=400.616262%
[pareto basket3] round=15, raw=31,127, local=541, materialized=526, frontier=183, beam=20, new=150, best_amount=0.16433002, best_TE=390.538293%
[pareto basket3] round=20, raw=22,859, local=479, materialized=453, frontier=223, beam=20, new=138, best_amount=0.16341704, best_TE=384.264492%
[pareto basket3] round=25, raw=20,539, local=456, materialized=429, frontier=255, beam=20, new=155, best_amount=0.16306506, best_TE=378.157193%
[pareto basket3] round=30, raw=22,609, local=447, materialized=432, frontier=321, beam=20, new=194, best_amount=0.16296135, best_TE=373.338186%
[pareto basket3] round=35, raw=18,140, local=551, materialized=530, frontier=335, beam=20, new=231, best_amount=0.16265897, best_TE=369.245244%
[pareto basket3] round=40, raw=14,136, local=450, materialized=427, frontier=478, beam=20, new=171, best_amount=0.16265897, best_TE=362.128642%
[pareto basket3] round=45, raw=15,222, local=350, materialized=328, frontier=436, beam=20, new=110, best_amount=0.16254400, best_TE=360.037698%
[pareto basket3] round=50, raw=17,584, local=439, materialized=417, frontier=463, beam=20, new=121, best_amount=0.16254400, best_TE=357.598115%
[11/19] Task8 20260715
[pareto basket3] round=1, raw=2,931, local=38, materialized=38, frontier=38, beam=20, new=38, best_amount=0.17370888, best_TE=510.935038%
[pareto basket3] round=5, raw=62,827, local=415, materialized=399, frontier=63, beam=20, new=63, best_amount=0.16689539, best_TE=399.979647%
[pareto basket3] round=10, raw=31,695, local=526, materialized=520, frontier=122, beam=20, new=121, best_amount=0.16216505, best_TE=374.293722%
[pareto basket3] round=15, raw=23,909, local=529, materialized=518, frontier=176, beam=20, new=161, best_amount=0.15985372, best_TE=363.248008%
[pareto basket3] round=20, raw=20,410, local=396, materialized=385, frontier=159, beam=20, new=113, best_amount=0.15871503, best_TE=355.130095%
[pareto basket3] round=25, raw=15,532, local=409, materialized=395, frontier=190, beam=20, new=117, best_amount=0.15851916, best_TE=351.666656%
[pareto basket3] round=30, raw=13,946, local=374, materialized=368, frontier=236, beam=20, new=99, best_amount=0.15839721, best_TE=348.775072%
[pareto basket3] round=35, raw=12,853, local=342, materialized=285, frontier=297, beam=20, new=100, best_amount=0.15839721, best_TE=344.549896%
[pareto basket3] round=40, raw=12,027, local=273, materialized=249, frontier=223, beam=20, new=86, best_amount=0.15818461, best_TE=343.148350%
[pareto basket3] round=45, raw=12,560, local=306, materialized=299, frontier=229, beam=20, new=84, best_amount=0.15818461, best_TE=342.963805%
[pareto basket3] round=50, raw=13,767, local=334, materialized=285, frontier=213, beam=20, new=56, best_amount=0.15818461, best_TE=342.453236%
[12/19] Task8 20260716
[pareto basket3] round=1, raw=2,127, local=42, materialized=42, frontier=42, beam=20, new=42, best_amount=0.16963249, best_TE=507.531459%
[pareto basket3] round=5, raw=49,178, local=773, materialized=769, frontier=93, beam=20, new=93, best_amount=0.16430532, best_TE=382.150740%
[pareto basket3] round=10, raw=46,147, local=577, materialized=567, frontier=114, beam=20, new=114, best_amount=0.16106688, best_TE=360.770829%
[pareto basket3] round=15, raw=26,087, local=488, materialized=477, frontier=118, beam=20, new=102, best_amount=0.15906829, best_TE=348.504659%
[pareto basket3] round=20, raw=36,232, local=376, materialized=333, frontier=169, beam=20, new=83, best_amount=0.15833491, best_TE=338.816699%
[pareto basket3] round=25, raw=19,856, local=440, materialized=424, frontier=221, beam=20, new=154, best_amount=0.15741966, best_TE=332.763691%
[pareto basket3] round=30, raw=20,201, local=400, materialized=358, frontier=272, beam=20, new=147, best_amount=0.15732377, best_TE=328.172245%
[pareto basket3] round=35, raw=18,068, local=319, materialized=309, frontier=230, beam=20, new=122, best_amount=0.15704961, best_TE=326.561138%
[pareto basket3] round=40, raw=19,514, local=304, materialized=296, frontier=244, beam=20, new=93, best_amount=0.15689280, best_TE=324.389106%
[pareto basket3] round=45, raw=17,769, local=288, materialized=279, frontier=231, beam=20, new=109, best_amount=0.15689280, best_TE=324.389106%
[pareto basket3] round=50, raw=17,953, local=183, materialized=175, frontier=266, beam=20, new=58, best_amount=0.15689280, best_TE=321.769114%
[13/19] Task8 20260721
[pareto basket3] round=1, raw=2,244, local=43, materialized=43, frontier=43, beam=20, new=43, best_amount=0.16822735, best_TE=549.784316%
[pareto basket3] round=5, raw=53,025, local=593, materialized=568, frontier=75, beam=20, new=75, best_amount=0.16297944, best_TE=407.127016%
[pareto basket3] round=10, raw=32,625, local=379, materialized=371, frontier=111, beam=20, new=111, best_amount=0.15833030, best_TE=376.336942%
[pareto basket3] round=15, raw=24,110, local=447, materialized=420, frontier=170, beam=20, new=143, best_amount=0.15640732, best_TE=361.681120%
[pareto basket3] round=20, raw=22,607, local=540, materialized=530, frontier=216, beam=20, new=189, best_amount=0.15507118, best_TE=352.741707%

,construction_date,basket3_invested_amount,basket3_held_stock_count,excluded_component_count
0,20260701,4522118.70,277,2
1,20260702,4501427.93,277,3
2,20260703,4519745.01,276,2
3,20260706,4522371.80,278,2
4,20260707,4517775.98,276,5
5,20260708,4509839.30,280,2
6,20260709,4506748.11,279,2
7,20260710,4502238.37,277,1
8,20260713,4515602.96,278,1
9,20260714,4502913.39,277,1
10,20260715,4509609.30,278,1
11,20260716,4502073.99,278,1
12,20260721,4520997.77,282,1
13,20260722,4512263.76,282,2
14,20260723,4522381.24,283,1
15,20260724,4500814.19,282,1
16,20260727,4500047.77,280,1
17,20260730,4519109.85,279,3
18,20260731,4520110.86,280,1

## Task9：逐日读取 D+1 指数 09:31 close

In [24]:
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task9 "
        f"{run.construction_date} -> {run.evaluation_date}"
    )
    run.load_index_opening_price()

display(
    pd.DataFrame(
        [
            {
                "construction_date": run.construction_date,
                "evaluation_date": run.evaluation_date,
                "construction_index_close": (
                    run.construction_index_close
                ),
                "opening_index_close": run.opening_index_close,
            }
            for run in date_runs
        ]
    )
)

[1/19] Task9 20260701 -> 20260702
[2/19] Task9 20260702 -> 20260703
[3/19] Task9 20260703 -> 20260706
[4/19] Task9 20260706 -> 20260707
[5/19] Task9 20260707 -> 20260708
[6/19] Task9 20260708 -> 20260709
[7/19] Task9 20260709 -> 20260710
[8/19] Task9 20260710 -> 20260713
[9/19] Task9 20260713 -> 20260714
[10/19] Task9 20260714 -> 20260715
[11/19] Task9 20260715 -> 20260716
[12/19] Task9 20260716 -> 20260717
[13/19] Task9 20260721 -> 20260722
[14/19] Task9 20260722 -> 20260723
[15/19] Task9 20260723 -> 20260724
[16/19] Task9 20260724 -> 20260727
[17/19] Task9 20260727 -> 20260728
[18/19] Task9 20260730 -> 20260731
[19/19] Task9 20260731 -> 20260803

,construction_date,evaluation_date,construction_index_close,opening_index_close
0,20260701,20260702,4958.9773,4864.983
1,20260702,20260703,4812.2957,4829.190
2,20260703,20260706,4842.1737,4855.503
3,20260706,20260707,4841.9980,4808.960
4,20260707,20260708,4792.2624,4798.470
5,20260708,20260709,4755.5338,4775.219
6,20260709,20260710,4876.3125,4885.546
7,20260710,20260713,4780.7867,4752.512
8,20260713,20260714,4695.3830,4705.830
9,20260714,20260715,4796.5020,4792.022
10,20260715,20260716,4786.7828,4723.722
11,20260716,20260717,4698.4344,4654.778
12,20260721,20260722,4739.2287,4723.764
13,20260722,20260723,4717.2442,4719.985
14,20260723,20260724,4728.0018,4670.288
15,20260724,20260727,4649.1917,4640.961
16,20260727,20260728,4702.4272,4622.041
17,20260730,20260731,4549.7201,4617.568
18,20260731,20260803,4588.1968,4557.787

## Task10：逐日计算 basket1 和 basket3 的 09:31 偏差

In [25]:
task11_summary_by_date = {}
for position, run in enumerate(date_runs, start=1):
    print(
        f"[{position}/{len(date_runs)}] Task10 "
        f"{run.construction_date}"
    )
    task11_summary_by_date[run.construction_date] = run.evaluate()

[1/19] Task10 20260701
[2/19] Task10 20260702
[3/19] Task10 20260703
[4/19] Task10 20260706
[5/19] Task10 20260707
[6/19] Task10 20260708
[7/19] Task10 20260709
[8/19] Task10 20260710
[9/19] Task10 20260713
[10/19] Task10 20260714
[11/19] Task10 20260715
[12/19] Task10 20260716
[13/19] Task10 20260721
[14/19] Task10 20260722
[15/19] Task10 20260723
[16/19] Task10 20260724
[17/19] Task10 20260727
[18/19] Task10 20260730
[19/19] Task10 20260731

## Task11：汇总两个篮子并使用 Plotly 绘图

核心表 `df_deviation_summary_all` 每个构建日固定按 basket1、basket3 输出两行，共 `2 * len(construction_date_ls)` 行、9 列。随后使用 Plotly 绘制 `common_base_gap_pct`、`return_gap_pct`、`cash_adjusted_gap_pct` 三张交互折线图；第一张图的副轴为 `common_base_gap_amount`。

In [26]:
df_deviation_summary_all = combine_task11_summaries(
    task11_summary_by_date,
    construction_date_ls,
)
# 保留原 notebook 常用变量名，现指向批量大表。
df_deviation_summary = df_deviation_summary_all

task11_report_path = (
    batch_reports_dir
    / "all_dates_two_basket_deviation_0931.csv"
)
df_deviation_summary_all.to_csv(
    task11_report_path,
    index=False,
    encoding="utf-8-sig",
)

assert len(df_deviation_summary_all) == 2 * len(
    construction_date_ls
)
assert (
    df_deviation_summary_all.groupby(
        "construction_date", sort=False
    ).size() == 2
).all()

print("Task11 批量报表:", task11_report_path)
display(df_deviation_summary_all)

Task11 批量报表: E:\Codex\系统\Stock-Index-Fitting\data\000300\20260807-165523_limit_impact_v01_batch\04_reports\all_dates_two_basket_deviation_0931.csv

,construction_date,basket,held_stock_count,basket_build_amount,basket_amount_0931,common_base_gap_amount,common_base_gap_pct,return_gap_pct,cash_adjusted_gap_pct
0,20260701,basket1,274,4514954.90,4429744.52,367.754297,0.008303,0.008145,0.008303
1,20260701,basket3,277,4522118.70,4436373.52,6996.754297,0.157963,-0.000691,-0.003771
2,20260702,basket1,278,4514452.07,4530177.75,-122.994388,-0.002715,-0.002724,-0.002715
3,20260702,basket3,277,4501427.93,4517462.81,-12837.934388,-0.283379,0.005152,0.004110
4,20260703,basket1,281,4509257.47,4520331.78,-1338.554411,-0.029603,-0.029685,-0.029603
5,20260703,basket3,276,4519745.01,4531052.11,9381.775589,0.207485,-0.025104,-0.024455
6,20260706,basket1,281,4519512.45,4492109.59,3434.751317,0.076520,0.075998,0.076520
7,20260706,basket3,278,4522371.80,4493889.40,5214.561317,0.116172,0.052511,0.052470
8,20260707,basket1,277,4518819.08,4520311.97,-4360.508454,-0.096372,-0.096497,-0.096372
9,20260707,basket3,276,4517775.98,4518494.85,-6177.628454,-0.136532,-0.113622,-0.113478
10,20260708,basket1,277,4500072.13,4520230.26,1530.395739,0.033868,0.034008,0.033868
11,20260708,basket3,280,4509839.30,4530285.63,11585.765739,0.256396,0.039429,0.040246
12,20260709,basket1,282,4521931.72,4530281.19,-212.995292,-0.004701,-0.004710,-0.004701
13,20260709,basket3,279,4506748.11,4514134.24,-16359.945292,-0.361107,-0.025464,-0.025965
14,20260710,basket1,282,4517055.81,4491464.60,1123.723321,0.025025,0.024877,0.025025
15,20260710,basket3,277,4502238.37,4478853.12,-11487.756679,-0.255833,0.072010,0.074152
16,20260713,basket1,281,4500084.89,4503038.39,-7058.971154,-0.156515,-0.156863,-0.156515
17,20260713,basket3,278,4515602.96,4518472.65,8375.288846,0.185701,-0.158945,-0.158373
18,20260714,basket1,281,4505582.12,4501313.82,-60.023240,-0.001333,-0.001332,-0.001333
19,20260714,basket3,277,4502913.39,4498024.72,-3349.123240,-0.074402,-0.015165,-0.015115
20,20260715,basket1,278,4503950.22,4444743.96,128.519935,0.002892,0.002853,0.002892
21,20260715,basket3,278,4509609.30,4450318.20,5702.759935,0.128307,0.002622,0.000983
22,20260716,basket1,279,4500117.63,4459199.53,895.601880,0.020088,0.019902,0.020088
23,20260716,basket3,278,4502073.99,4460866.73,2562.801880,0.057484,0.013874,0.013603
24,20260721,basket1,281,4513863.04,4499492.73,358.993474,0.007979,0.007953,0.007979
25,20260721,basket3,282,4520997.77,4507113.11,7979.373474,0.177354,0.019198,0.018773
26,20260722,basket1,282,4512848.20,4513856.96,-1613.282409,-0.035728,-0.035749,-0.035728
27,20260722,basket3,282,4512263.76,4511836.32,-3633.922409,-0.080477,-0.067575,-0.067534
28,20260723,basket1,281,4512487.11,4459684.39,2280.334023,0.051158,0.050534,0.051158
29,20260723,basket3,283,4522381.24,4469273.37,11869.314023,0.266283,0.046346,0.044312
30,20260724,basket1,284,4504833.10,4497787.76,929.794645,0.020677,0.020640,0.020677
31,20260724,basket3,282,4500814.19,4493961.15,-2896.815355,-0.064419,0.024773,0.024953
32,20260727,basket1,283,4520988.49,4448870.96,5167.044433,0.116278,0.114290,0.116278
33,20260727,basket3,280,4500047.77,4427889.91,-15814.005567,-0.355874,0.105971,0.115370
34,20260730,basket1,281,4520274.11,4582958.71,-4724.185386,-0.102975,-0.104511,-0.102975
35,20260730,basket3,279,4519109.85,4582264.75,-5418.145386,-0.118102,-0.093747,-0.092724
36,20260731,basket1,281,4519385.68,4493213.81,3781.861421,0.084239,0.083681,0.084239
37,20260731,basket3,280,4520110.86,4494137.46,4705.511421,0.104813,0.088165,0.088660

In [13]:
required_plot_columns = {
    "construction_date",
    "basket",
    "common_base_gap_pct",
    "common_base_gap_amount",
    "return_gap_pct",
    "cash_adjusted_gap_pct",
}
missing_columns = required_plot_columns - set(
    df_deviation_summary_all.columns
)
if missing_columns:
    raise ValueError(
        f"绘图数据缺少字段: {sorted(missing_columns)}"
    )

basket_order = ["basket1", "basket3"]
basket_colors = {
    "basket1": "#1f77b4",
    "basket3": "#2ca02c",
}

plot_df = df_deviation_summary_all.copy()
plot_df["construction_date"] = pd.to_datetime(
    plot_df["construction_date"].astype(str),
    format="%Y%m%d",
)
plot_df["basket"] = pd.Categorical(
    plot_df["basket"],
    categories=basket_order,
    ordered=True,
)
plot_df = plot_df.sort_values(
    ["construction_date", "basket"]
).reset_index(drop=True)

if plot_df[list(required_plot_columns)].isna().any(axis=None):
    bad_rows = plot_df.loc[
        plot_df[list(required_plot_columns)].isna().any(axis=1)
    ]
    display(bad_rows)
    raise ValueError("绘图数据中存在缺失值")

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def plot_metric_plotly(
    data,
    metric,
    title,
    *,
    secondary_amount=False,
):
    fig = make_subplots(
        specs=[[{"secondary_y": secondary_amount}]]
    )

    # 主轴：basket1 和 basket3 的百分比指标。
    for basket in basket_order:
        basket_data = data.loc[data["basket"] == basket]
        fig.add_trace(
            go.Scatter(
                x=basket_data["construction_date"],
                y=basket_data[metric],
                mode="lines+markers",
                name=f"{basket} - {metric}",
                line={
                    "color": basket_colors[basket],
                    "width": 2.5,
                },
                marker={"size": 7},
                hovertemplate=(
                    "%{x|%Y-%m-%d}"
                    f"<br>{basket}"
                    f"<br>{metric}: %{{y:.6f}}%"
                    "<extra></extra>"
                ),
            ),
            secondary_y=False,
        )

    # 第一张图副轴：两个篮子的 common_base_gap_amount。
    if secondary_amount:
        for basket in basket_order:
            basket_data = data.loc[data["basket"] == basket]
            fig.add_trace(
                go.Scatter(
                    x=basket_data["construction_date"],
                    y=basket_data["common_base_gap_amount"],
                    mode="lines+markers",
                    name=(
                        f"{basket} - common_base_gap_amount"
                    ),
                    line={
                        "color": basket_colors[basket],
                        "width": 1.8,
                        "dash": "dash",
                    },
                    marker={"size": 7, "symbol": "x"},
                    opacity=0.75,
                    hovertemplate=(
                        "%{x|%Y-%m-%d}"
                        f"<br>{basket}"
                        "<br>common_base_gap_amount: "
                        "%{y:,.2f}"
                        "<extra></extra>"
                    ),
                ),
                secondary_y=True,
            )

    fig.add_hline(
        y=0,
        line_width=1,
        line_dash="dot",
        line_color="black",
        secondary_y=False,
    )
    fig.update_layout(
        title=title,
        xaxis_title="Construction Date",
        template="plotly_white",
        hovermode="x unified",
        width=1100,
        height=600,
        legend={
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "left",
            "x": 0,
        },
        margin={"t": 120},
    )
    fig.update_xaxes(
        tickformat="%Y-%m-%d",
        showgrid=True,
    )
    fig.update_yaxes(
        title_text=f"{metric}（%）",
        ticksuffix="%",
        showgrid=True,
        secondary_y=False,
    )
    if secondary_amount:
        fig.update_yaxes(
            title_text="common_base_gap_amount",
            tickformat=",.0f",
            showgrid=False,
            secondary_y=True,
        )

    fig.show()
    return fig


plotly_figures = {
    "common_base_gap": plot_metric_plotly(
        plot_df,
        "common_base_gap_pct",
        "Basket Common Base Gap",
        secondary_amount=True,
    ),
    "return_gap": plot_metric_plotly(
        plot_df,
        "return_gap_pct",
        "Basket Return Gap",
    ),
    "cash_adjusted_gap": plot_metric_plotly(
        plot_df,
        "cash_adjusted_gap_pct",
        "Basket Cash-adjusted Gap",
    ),
}

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def plot_metric_plotly(
    data,
    metric,
    title,
    *,
    secondary_amount=False,
):
    fig = make_subplots(
        specs=[[{"secondary_y": secondary_amount}]]
    )

    # 主轴：basket1 和 basket3 的百分比指标。
    for basket in basket_order:
        basket_data = data.loc[data["basket"] == basket]
        fig.add_trace(
            go.Scatter(
                x=basket_data["construction_date"],
                y=basket_data[metric],
                mode="lines+markers",
                name=f"{basket} - {metric}",
                line={
                    "color": basket_colors[basket],
                    "width": 2.5,
                },
                marker={"size": 7},
                hovertemplate=(
                    "%{x|%Y-%m-%d}"
                    f"<br>{basket}"
                    f"<br>{metric}: %{{y:.6f}}%"
                    "<extra></extra>"
                ),
            ),
            secondary_y=False,
        )

    # 第一张图副轴：两个篮子的 common_base_gap_amount。
    if secondary_amount:
        for basket in basket_order:
            basket_data = data.loc[data["basket"] == basket]
            fig.add_trace(
                go.Scatter(
                    x=basket_data["construction_date"],
                    y=basket_data["common_base_gap_amount"],
                    mode="lines+markers",
                    name=(
                        f"{basket} - common_base_gap_amount"
                    ),
                    line={
                        "color": basket_colors[basket],
                        "width": 1.8,
                        "dash": "dash",
                    },
                    marker={"size": 7, "symbol": "x"},
                    opacity=0.75,
                    hovertemplate=(
                        "%{x|%Y-%m-%d}"
                        f"<br>{basket}"
                        "<br>common_base_gap_amount: "
                        "%{y:,.2f}"
                        "<extra></extra>"
                    ),
                ),
                secondary_y=True,
            )

    fig.add_hline(
        y=0,
        line_width=1,
        line_dash="dot",
        line_color="black",
        secondary_y=False,
    )
    fig.update_layout(
        title=title,
        xaxis_title="Construction Date",
        template="plotly_white",
        hovermode="x unified",
        width=1100,
        height=600,
        legend={
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "left",
            "x": 0,
        },
        margin={"t": 120},
    )
    fig.update_xaxes(
        tickformat="%Y-%m-%d",
        showgrid=True,
    )
    fig.update_yaxes(
        title_text=f"{metric}（%）",
        ticksuffix="%",
        showgrid=True,
        secondary_y=False,
    )
    if secondary_amount:
        fig.update_yaxes(
            title_text="common_base_gap_amount",
            tickformat=",.0f",
            showgrid=False,
            secondary_y=True,
        )

    fig.show()
    return fig


plotly_figures = {
    "common_base_gap": plot_metric_plotly(
        plot_df,
        "common_base_gap_pct",
        "Basket Common Base Gap",
        secondary_amount=True,
    ),
    "return_gap": plot_metric_plotly(
        plot_df,
        "return_gap_pct",
        "Basket Return Gap",
    ),
    "cash_adjusted_gap": plot_metric_plotly(
        plot_df,
        "cash_adjusted_gap_pct",
        "Basket Cash-adjusted Gap",
    ),
}

In [14]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def plot_metric_plotly(
    data,
    metric,
    title,
    *,
    secondary_amount=False,
):
    fig = make_subplots(
        specs=[[{"secondary_y": secondary_amount}]]
    )

    # 主轴：basket1 和 basket3 的百分比指标。
    for basket in basket_order:
        basket_data = data.loc[data["basket"] == basket]
        fig.add_trace(
            go.Scatter(
                x=basket_data["construction_date"],
                y=basket_data[metric],
                mode="lines+markers",
                name=f"{basket} - {metric}",
                line={
                    "color": basket_colors[basket],
                    "width": 2.5,
                },
                marker={"size": 7},
                hovertemplate=(
                    "%{x|%Y-%m-%d}"
                    f"<br>{basket}"
                    f"<br>{metric}: %{{y:.6f}}%"
                    "<extra></extra>"
                ),
            ),
            secondary_y=False,
        )

    # 第一张图副轴：两个篮子的 common_base_gap_amount。
    if secondary_amount:
        for basket in basket_order:
            basket_data = data.loc[data["basket"] == basket]
            fig.add_trace(
                go.Scatter(
                    x=basket_data["construction_date"],
                    y=basket_data["common_base_gap_amount"],
                    mode="lines+markers",
                    name=(
                        f"{basket} - common_base_gap_amount"
                    ),
                    line={
                        "color": basket_colors[basket],
                        "width": 1.8,
                        "dash": "dash",
                    },
                    marker={"size": 7, "symbol": "x"},
                    opacity=0.75,
                    hovertemplate=(
                        "%{x|%Y-%m-%d}"
                        f"<br>{basket}"
                        "<br>common_base_gap_amount: "
                        "%{y:,.2f}"
                        "<extra></extra>"
                    ),
                ),
                secondary_y=True,
            )

    fig.add_hline(
        y=0,
        line_width=1,
        line_dash="dot",
        line_color="black",
        secondary_y=False,
    )
    fig.update_layout(
        title=title,
        xaxis_title="Construction Date",
        template="plotly_white",
        hovermode="x unified",
        width=1100,
        height=600,
        legend={
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "left",
            "x": 0,
        },
        margin={"t": 120},
    )
    fig.update_xaxes(
        tickformat="%Y-%m-%d",
        showgrid=True,
    )
    fig.update_yaxes(
        title_text=f"{metric}（%）",
        ticksuffix="%",
        showgrid=True,
        secondary_y=False,
    )
    if secondary_amount:
        fig.update_yaxes(
            title_text="common_base_gap_amount",
            tickformat=",.0f",
            showgrid=False,
            secondary_y=True,
        )

    fig.show()
    return fig


plotly_figures = {
    "common_base_gap": plot_metric_plotly(
        plot_df,
        "common_base_gap_pct",
        "Basket Common Base Gap",
        secondary_amount=True,
    ),
    "return_gap": plot_metric_plotly(
        plot_df,
        "return_gap_pct",
        "Basket Return Gap",
    ),
    "cash_adjusted_gap": plot_metric_plotly(
        plot_df,
        "cash_adjusted_gap_pct",
        "Basket Cash-adjusted Gap",
    ),
}

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def plot_metric_plotly(
    data,
    metric,
    title,
    *,
    secondary_amount=False,
):
    fig = make_subplots(
        specs=[[{"secondary_y": secondary_amount}]]
    )

    # 主轴：basket1 和 basket3 的百分比指标。
    for basket in basket_order:
        basket_data = data.loc[data["basket"] == basket]
        fig.add_trace(
            go.Scatter(
                x=basket_data["construction_date"],
                y=basket_data[metric],
                mode="lines+markers",
                name=f"{basket} - {metric}",
                line={
                    "color": basket_colors[basket],
                    "width": 2.5,
                },
                marker={"size": 7},
                hovertemplate=(
                    "%{x|%Y-%m-%d}"
                    f"<br>{basket}"
                    f"<br>{metric}: %{{y:.6f}}%"
                    "<extra></extra>"
                ),
            ),
            secondary_y=False,
        )

    # 第一张图副轴：两个篮子的 common_base_gap_amount。
    if secondary_amount:
        for basket in basket_order:
            basket_data = data.loc[data["basket"] == basket]
            fig.add_trace(
                go.Scatter(
                    x=basket_data["construction_date"],
                    y=basket_data["common_base_gap_amount"],
                    mode="lines+markers",
                    name=(
                        f"{basket} - common_base_gap_amount"
                    ),
                    line={
                        "color": basket_colors[basket],
                        "width": 1.8,
                        "dash": "dash",
                    },
                    marker={"size": 7, "symbol": "x"},
                    opacity=0.75,
                    hovertemplate=(
                        "%{x|%Y-%m-%d}"
                        f"<br>{basket}"
                        "<br>common_base_gap_amount: "
                        "%{y:,.2f}"
                        "<extra></extra>"
                    ),
                ),
                secondary_y=True,
            )

    fig.add_hline(
        y=0,
        line_width=1,
        line_dash="dot",
        line_color="black",
        secondary_y=False,
    )
    fig.update_layout(
        title=title,
        xaxis_title="Construction Date",
        template="plotly_white",
        hovermode="x unified",
        width=1100,
        height=600,
        legend={
            "orientation": "h",
            "yanchor": "bottom",
            "y": 1.02,
            "xanchor": "left",
            "x": 0,
        },
        margin={"t": 120},
    )
    fig.update_xaxes(
        tickformat="%Y-%m-%d",
        showgrid=True,
    )
    fig.update_yaxes(
        title_text=f"{metric}（%）",
        ticksuffix="%",
        showgrid=True,
        secondary_y=False,
    )
    if secondary_amount:
        fig.update_yaxes(
            title_text="common_base_gap_amount",
            tickformat=",.0f",
            showgrid=False,
            secondary_y=True,
        )

    fig.show()
    return fig


plotly_figures = {
    "common_base_gap": plot_metric_plotly(
        plot_df,
        "common_base_gap_pct",
        "Basket Common Base Gap",
        secondary_amount=True,
    ),
    "return_gap": plot_metric_plotly(
        plot_df,
        "return_gap_pct",
        "Basket Return Gap",
    ),
    "cash_adjusted_gap": plot_metric_plotly(
        plot_df,
        "cash_adjusted_gap_pct",
        "Basket Cash-adjusted Gap",
    ),
}