# 指数权重清单推算

使用最近一次官方权重清单、成分股日收盘价和公司送转股行为，推算目标交易日的指数权重清单。

## 参数设置

In [1]:
from __future__ import annotations

from pathlib import Path
import sys
import pandas as pd
from IPython.display import display
from datetime import datetime

PROJECT_ROOT = Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utils import gogoal_query
from utils.weight_projection import (
    fetch_corporate_actions,
    fetch_stock_closes_range,
    load_or_download_weight_source,
    make_projection_output_dir,
    normalize_date_key,
    project_weights_by_close_and_actions,
    save_projection_outputs,
    select_weight_source_for_target,
)

# 指数代码，例如 000016 / 000300 / 000905 / 000852。
INDEX_CODE = "000300"

# 目标日期，YYYYMMDD。
target_date = "20260615"

# 本地历史权重清单日期。选择规则为：日期 <= target_date，并取最接近 target_date 的日期。
# 新增历史清单时，在这里追加 YYYYMMDD；文件名须为 沪深300_样本权重_YYYYMMDD.csv。
HISTORICAL_WEIGHT_DATES = [
    "20250731", "20250829", "20250930", "20251031",
    "20251128", "20251231", "20260130", "20260227",
    "20260331", "20260430", "20260529", "20260630",
]
historical_weight_dir = PROJECT_ROOT / "data" / "weights_projection"
historical_weight_files = {
    date: historical_weight_dir / f"沪深300_样本权重_{date}.csv"
    for date in HISTORICAL_WEIGHT_DATES
}

# 输出目录；None 时自动写入 ./data/weights_projection/。
# 基准日和之后的每个交易日均保存为 f"{INDEX_CODE}-{current_date}.csv"。
output_dir = None

In [2]:
from xtquant import xtdata
xtdata.reconnect(port = 58610)

***** xtdata连接成功 2026-07-27 16:06:36*****
服务信息: {'tag': 'qmt_research', 'version': '1.0'}
服务地址: 127.0.0.1:58610
数据路径: E:\迅投极速交易终端睿智融科版\datadir
设置xtdata.enable_hello = False可隐藏此消息

## 读取或下载源权重清单

In [3]:
download_dir = PROJECT_ROOT / "data" / INDEX_CODE / "weight_projection" / "source_files"
latest_weights, latest_source_path = load_or_download_weight_source(
    index_code=INDEX_CODE,
    file_path=None,
    output_dir=download_dir,
)
target_date = normalize_date_key(target_date)

source_selection = select_weight_source_for_target(
    target_date=target_date,
    latest_weights=latest_weights,
    latest_source_path=latest_source_path,
    historical_weight_files=historical_weight_files,
)
source_weights = source_selection.weights
source_weight_path = source_selection.source_path
source_weight_date = source_selection.source_date

print("Latest downloaded weight date:", source_selection.latest_source_date)
print("Selection mode:", source_selection.selection_mode)
print("Source weight path:", source_weight_path)
print("Source weight date:", source_weight_date)
print("Target date:", target_date)
print("Source weight rows:", len(source_weights))
print("Source weight sum pct:", source_weights["raw_weight_pct"].sum())
display(source_weights.head())

正在下载指数 000300 样本权重...
解析到真实链接: https://oss-ch.csindex.com.cn/static/html/csindex/public/uploads/file/autofile/closeweight/000300closeweight.xls
下载完成: E:\Codex\系统\Stock-Index-Fitting\data\000300\weight_projection\source_files\000300_样本权重_20260727.xls
     日期Date  指数代码 Index Code 指数名称 Index Name 指数英文名称Index Name(Eng)  \
0  20260630              300           沪深300               CSI 300
1  20260630              300           沪深300               CSI 300
2  20260630              300           沪深300               CSI 300
3  20260630              300           沪深300               CSI 300
4  20260630              300           沪深300               CSI 300

   成份券代码Constituent Code 成份券名称Constituent Name  \
0                      1                  平安银行
1                      2                   万科A
2                     63                  中兴通讯
3                    100                 TCL科技
4                    157                  中联重科

                        成份券英文名称Constituent Name(Eng) 交易所Exchange  \
0                             Ping An Bank Co., Ltd.     深圳证券交易所
1                                 China Vanke Co Ltd     深圳证券交易所
2                                    ZTE Corporation     深圳证券交易所
3                   TCL Technology Group Corporation     深圳证券交易所
4  Zoomlion Heavy Industry Science & Technology C...     深圳证券交易所

      交易所英文名称Exchange(Eng)  权重(%)weight
0  Shenzhen Stock Exchange        0.345
1  Shenzhen Stock Exchange        0.071
2  Shenzhen Stock Exchange        0.412
3  Shenzhen Stock Exchange        0.428
4  Shenzhen Stock Exchange        0.122
Latest downloaded weight date: 20260630
Selection mode: historical_local
Source weight path: E:\Codex\系统\Stock-Index-Fitting\data\weights_projection\沪深300_样本权重_20260529.csv
Source weight date: 20260529
Target date: 20260615
Source weight rows: 300
Source weight sum pct: 100.00399999999999

,stock_code,stock_name,raw_weight_pct,closeweight_data_date,source_path
0,000001.SZ,平安银行,0.397,20260529,E:\Codex\系统\Stock-Index-Fitting\data\weights_p...
1,000002.SZ,万科A,0.090,20260529,E:\Codex\系统\Stock-Index-Fitting\data\weights_p...
2,000063.SZ,中兴通讯,0.443,20260529,E:\Codex\系统\Stock-Index-Fitting\data\weights_p...
3,000100.SZ,TCL科技,0.333,20260529,E:\Codex\系统\Stock-Index-Fitting\data\weights_p...
4,000157.SZ,中联重科,0.134,20260529,E:\Codex\系统\Stock-Index-Fitting\data\weights_p...

## 查询日收盘价与公司行为

In [4]:
#Task5
def normalize_stock_code(value) -> str:
    raw = str(value).strip().upper()
    if raw.endswith((".SH", ".SZ", ".BJ")):
        return raw
    digits = raw.split(".")[0].zfill(6)
    return f"{digits}.SH" if digits.startswith(("5", "6", "9")) else f"{digits}.SZ"

def strip_market_suffix(value) -> str:
    return str(value).strip().upper().split(".")[0].zfill(6)

def normalize_trade_date_dash(value) -> str:
    return pd.Timestamp(value).strftime("%Y-%m-%d")

def sql_literal(value) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def sql_in(values) -> str:
    vals = list(values)
    if not vals:
        raise ValueError("SQL IN 列表为空")
    return ", ".join(sql_literal(v) for v in vals)

def fetch_gogoal_corporate_actions(stock_codes: list[str], start_date: str, end_date: str) -> pd.DataFrame:
    stripped_codes = [strip_market_suffix(code) for code in stock_codes]
    sql = f"""
        SELECT
            stock_code,
            stock_name,
            declare_date,
            xr_xd_date AS ex_date,
            beftax_maxcashdiv,
            beftax_mincashdiv,
            aftax_cashdiv,
            stockdiv_ratio,
            trans_ratio,
            bonus_ratio,
            is_newest,
            is_valid
        FROM bas_stk_hisdistribution
        WHERE stock_code IN ({sql_in(stripped_codes)})
          AND xr_xd_date >= {sql_literal(normalize_trade_date_dash(start_date))}
          AND xr_xd_date <= {sql_literal(normalize_trade_date_dash(end_date))}
          AND is_valid = 1
    """
    raw = gogoal_query(sql, output_format="dataframe")
    if raw.empty:
        return pd.DataFrame(columns=["stock_code", "ex_date"])
    raw["stock_code"] = raw["stock_code"].map(normalize_stock_code)
    raw["ex_date"] = pd.to_datetime(raw["ex_date"], errors="coerce").dt.strftime("%Y-%m-%d")
    return raw

stock_codes = source_weights["stock_code"].tolist()
# future_date = (pd.Timestamp(last_fitting_date) + timedelta(days=1)).strftime("%Y%m%d")
started_at = datetime.now().astimezone()
import_time = started_at.strftime("%Y%m%d-%H%M")

df_actions_gogoal = fetch_gogoal_corporate_actions(stock_codes, source_weight_date, target_date)
df_actions_gogoal["import_time"] = import_time

xt_action_frames = []
for stock_code in stock_codes:
    frame = xtdata.get_divid_factors(stock_code, source_weight_date, target_date)
    if frame is not None and not frame.empty:
        item = frame.copy().reset_index().rename(columns={"index": "ex_date"})
        item.insert(0, "stock_code", stock_code)
        xt_action_frames.append(item)
df_actions_xt = pd.concat(xt_action_frames, ignore_index=True) if xt_action_frames else pd.DataFrame(columns=["stock_code", "ex_date"])
if not df_actions_xt.empty:
    df_actions_xt["stock_code"] = df_actions_xt["stock_code"].map(normalize_stock_code)
    df_actions_xt["ex_date"] = pd.to_datetime(df_actions_xt["ex_date"], errors="coerce").dt.strftime("%Y-%m-%d")
df_actions_xt["import_time"] = import_time

left_keys = df_actions_gogoal[["stock_code", "ex_date"]].drop_duplicates()
right_keys = df_actions_xt[["stock_code", "ex_date"]].drop_duplicates()
df_actions_check = left_keys.merge(right_keys, on=["stock_code", "ex_date"], how="outer", indicator=True)
df_actions_check["is_consistent"] = df_actions_check["_merge"].eq("both")
df_actions_check["import_time"] = import_time
if df_actions_gogoal.empty and df_actions_xt.empty:
    df_actions_check = pd.DataFrame([{
        "stock_code": None,
        "ex_date": None,
        "_merge": "both",
        "is_consistent": True,
        "note": "Go-Goal 与迅投在查询窗口内均无公司行为事件",
        "import_time": import_time,
    }])

df_actions_merged = df_actions_gogoal.merge(
    df_actions_xt, on=["stock_code", "ex_date"], how="outer", suffixes=("_gogoal", "_xt")
)
df_actions_merged["import_time"] = import_time

daily_closes = fetch_stock_closes_range(
    gogoal_query,
    stock_codes=stock_codes,
    start_date=source_weight_date,
    end_date=target_date,
)

print("Daily close rows:", len(daily_closes))
print("Trading dates:", daily_closes["trade_date"].nunique())
print("Corporate action rows:", len(df_actions_merged))
display(daily_closes.head())
display(df_actions_merged.head())

正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库
正在尝试first_config连接: 192.168.1.30:3306
成功使用first_config连接数据库

Daily close rows: 3600
Trading dates: 12
Corporate action rows: 52

  trade_date stock_code stock_name  close_price
0   20260529  300251.SZ       光线传媒        12.75
1   20260529  600219.SH       南山铝业         5.20
2   20260529  600905.SH       三峡能源         4.17
3   20260529  300979.SZ       华利集团        34.18
4   20260529  600150.SH       中国船舶        37.38

,stock_code,stock_name,declare_date,ex_date,beftax_maxcashdiv,beftax_mincashdiv,aftax_cashdiv,stockdiv_ratio,trans_ratio,bonus_ratio,...,time,interest,stockBonus,stockGift,allotNum,allotPrice,gugai,dr,import_time_xt,import_time
0,000001.SZ,平安银行,2026-06-05,2026-06-12,3.60,None,3.60,None,NaN,None,...,1.781194e+12,0.360,0.0,0.0,0.0,0.0,0.0,1.032846,20260727-1636,20260727-1636
1,000100.SZ,TCL科技,2026-06-03,2026-06-11,0.90,None,0.90,None,NaN,None,...,1.781107e+12,0.090,0.0,0.0,0.0,0.0,0.0,1.018867,20260727-1636,20260727-1636
2,000630.SZ,铜陵有色,2026-05-29,2026-06-08,0.50,None,0.50,None,NaN,None,...,1.780848e+12,0.050,0.0,0.0,0.0,0.0,0.0,1.007530,20260727-1636,20260727-1636
3,000786.SZ,北新建材,2026-06-06,2026-06-12,6.85,None,6.85,None,NaN,None,...,1.781194e+12,0.685,0.0,0.0,0.0,0.0,0.0,1.032739,20260727-1636,20260727-1636
4,000807.SZ,云铝股份,2026-06-04,2026-06-10,3.79,None,3.79,None,NaN,None,...,1.781021e+12,0.379,0.0,0.0,0.0,0.0,0.0,1.014383,20260727-1636,20260727-1636

In [5]:
# stock_codes = source_weights["stock_code"].tolist()

# daily_closes = fetch_stock_closes_range(
#     gogoal_query,
#     stock_codes=stock_codes,
#     start_date=source_weight_date,
#     end_date=target_date,
# )
# corporate_actions = fetch_corporate_actions(
#     gogoal_query,
#     stock_codes=stock_codes,
#     start_date=source_weight_date,
#     end_date=target_date,
# )

# print("Daily close rows:", len(daily_closes))
# print("Trading dates:", daily_closes["trade_date"].nunique())
# print("Corporate action rows:", len(corporate_actions))
# display(daily_closes.head())
# display(corporate_actions.head())

## 推算并保存权重清单

In [6]:
corporate_actions = df_actions_merged
target_weights, trace, daily_summary, standardized_actions = project_weights_by_close_and_actions(
    source_weights=source_weights,
    daily_closes=daily_closes,
    corporate_actions=corporate_actions,
    target_date=target_date,
)

if output_dir is None:
    output_dir = make_projection_output_dir(PROJECT_ROOT)

projection_outputs = save_projection_outputs(
    target_weights=target_weights,
    trace=trace,
    daily_summary=daily_summary,
    source_weights=source_weights,
    standardized_actions=standardized_actions,
    output_dir=output_dir,
    target_date=target_date,
    index_code=INDEX_CODE,
)

print("Output dir:", projection_outputs.output_dir)
print("Target weights:", projection_outputs.target_path)
print("Daily summary:", projection_outputs.summary_path)
print("Saved projected weight files:", len(trace))
print("Projected weight sum pct:", target_weights["projected_weight_pct"].sum())
display(daily_summary.tail())
display(target_weights.head(20))

Output dir: E:\Codex\系统\Stock-Index-Fitting\data\weights_projection
Target weights: E:\Codex\系统\Stock-Index-Fitting\data\weights_projection\000300-20260615.csv
Daily summary: E:\Codex\系统\Stock-Index-Fitting\data\weights_projection\000300-20260615-daily_summary.csv
Saved projected weight files: 12
Projected weight sum pct: 100.0

,trade_date,stock_count,weight_sum_pct,action_count,share_action_count,cash_dividend_action_count
7,20260609,300,100.0,2,0,2
8,20260610,300,100.0,7,0,7
9,20260611,300,100.0,5,1,5
10,20260612,300,100.0,7,1,7
11,20260615,300,100.0,3,0,3

,trade_date,stock_code,stock_name,source_weight_date,source_weight_pct,projected_weight_pct,base_close,close_price,share_factor,relative_value,cumulative_cash_dividend_per_base_share
0,20260615,300308.SZ,中际旭创,20260529,4.830,5.133250,1161.16,1245.00,1.0,0.051787,0.000
1,20260615,300750.SZ,宁德时代,20260529,4.198,3.906940,424.00,398.10,1.0,0.039416,0.000
2,20260615,300502.SZ,新易盛,20260529,2.629,3.588702,706.45,540.49,1.8,0.036205,2.000
3,20260615,600519.SH,贵州茅台,20260529,3.108,2.953148,1326.00,1271.10,1.0,0.029793,0.000
4,20260615,601318.SH,中国平安,20260529,2.135,2.145121,53.50,54.23,1.0,0.021641,3.500
5,20260615,601899.SH,紫金矿业,20260529,1.877,1.913686,30.44,31.31,1.0,0.019306,0.000
6,20260615,600036.SH,招商银行,20260529,1.761,1.788698,38.01,38.95,1.0,0.018046,0.000
7,20260615,688256.SH,寒武纪,20260529,1.541,1.556613,1310.00,1335.00,1.0,0.015704,0.000
8,20260615,000333.SZ,美的集团,20260529,1.490,1.478372,80.85,80.93,1.0,0.014915,0.000
9,20260615,002475.SZ,立讯精密,20260529,1.399,1.289457,73.29,68.15,1.0,0.013009,0.000
10,20260615,603986.SH,兆易创新,20260529,1.168,1.284146,467.01,518.00,1.0,0.012955,0.000
11,20260615,600900.SH,长江电力,20260529,1.271,1.251663,27.75,27.57,1.0,0.012628,0.000
12,20260615,601166.SH,兴业银行,20260529,1.173,1.145727,18.50,18.23,1.0,0.011559,0.501
13,20260615,002384.SZ,东山精密,20260529,1.023,1.138998,213.05,239.31,1.0,0.011491,0.000
14,20260615,002371.SZ,北方华创,20260529,1.021,1.096143,629.87,682.22,1.0,0.011059,0.000
15,20260615,601138.SH,工业富联,20260529,1.091,1.081416,73.40,73.40,1.0,0.010910,0.000
16,20260615,688041.SH,海光信息,20260529,1.023,1.032713,293.90,299.32,1.0,0.010419,0.000
17,20260615,688008.SH,澜起科技,20260529,1.085,1.020633,253.00,240.10,1.0,0.010297,0.000
18,20260615,600030.SH,中信证券,20260529,0.952,0.972979,26.05,26.86,1.0,0.009816,0.410
19,20260615,688981.SH,中芯国际,20260529,1.047,0.968151,139.91,130.52,1.0,0.009767,0.000

## 可选：查看某一天的推算轨迹

In [7]:
# 已保存源权重日、其后至 target_date 当日的全部交易日推算结果。
# 每个文件表示：使用 current_date 闭市后的 close price 估计次日指数将使用的权重清单。
if trace:
    saved_dates = sorted(trace)
    print("Saved date range:", saved_dates[0], "->", saved_dates[-1])
    print("Saved files:", len(saved_dates))
    display(trace[saved_dates[-1]].head(20))
else:
    print("没有中间交易日需要保存。")

Saved date range: 20260529 -> 20260615
Saved files: 12

,trade_date,stock_code,stock_name,source_weight_date,source_weight_pct,projected_weight_pct,base_close,close_price,share_factor,relative_value,cumulative_cash_dividend_per_base_share
0,20260615,300308.SZ,中际旭创,20260529,4.830,5.133250,1161.16,1245.00,1.0,0.051787,0.000
1,20260615,300750.SZ,宁德时代,20260529,4.198,3.906940,424.00,398.10,1.0,0.039416,0.000
2,20260615,300502.SZ,新易盛,20260529,2.629,3.588702,706.45,540.49,1.8,0.036205,2.000
3,20260615,600519.SH,贵州茅台,20260529,3.108,2.953148,1326.00,1271.10,1.0,0.029793,0.000
4,20260615,601318.SH,中国平安,20260529,2.135,2.145121,53.50,54.23,1.0,0.021641,3.500
5,20260615,601899.SH,紫金矿业,20260529,1.877,1.913686,30.44,31.31,1.0,0.019306,0.000
6,20260615,600036.SH,招商银行,20260529,1.761,1.788698,38.01,38.95,1.0,0.018046,0.000
7,20260615,688256.SH,寒武纪,20260529,1.541,1.556613,1310.00,1335.00,1.0,0.015704,0.000
8,20260615,000333.SZ,美的集团,20260529,1.490,1.478372,80.85,80.93,1.0,0.014915,0.000
9,20260615,002475.SZ,立讯精密,20260529,1.399,1.289457,73.29,68.15,1.0,0.013009,0.000
10,20260615,603986.SH,兆易创新,20260529,1.168,1.284146,467.01,518.00,1.0,0.012955,0.000
11,20260615,600900.SH,长江电力,20260529,1.271,1.251663,27.75,27.57,1.0,0.012628,0.000
12,20260615,601166.SH,兴业银行,20260529,1.173,1.145727,18.50,18.23,1.0,0.011559,0.501
13,20260615,002384.SZ,东山精密,20260529,1.023,1.138998,213.05,239.31,1.0,0.011491,0.000
14,20260615,002371.SZ,北方华创,20260529,1.021,1.096143,629.87,682.22,1.0,0.011059,0.000
15,20260615,601138.SH,工业富联,20260529,1.091,1.081416,73.40,73.40,1.0,0.010910,0.000
16,20260615,688041.SH,海光信息,20260529,1.023,1.032713,293.90,299.32,1.0,0.010419,0.000
17,20260615,688008.SH,澜起科技,20260529,1.085,1.020633,253.00,240.10,1.0,0.010297,0.000
18,20260615,600030.SH,中信证券,20260529,0.952,0.972979,26.05,26.86,1.0,0.009816,0.410
19,20260615,688981.SH,中芯国际,20260529,1.047,0.968151,139.91,130.52,1.0,0.009767,0.000